### ISSUE TITLE
The customized server error codes

### ISSUE THREAD

**Issue by boundless-forest** [paritytech/jsonrpsee#1001]
According to https://www.jsonrpc.org/specification#parameter_structures:

>  -32000 to -32099 | Server error | Reserved for implementation-defined server-errors.

```rs
/// Oversized response error code.
pub const OVERSIZED_RESPONSE_CODE: i32 = -32702;
/// Server is busy error code.
pub const SERVER_IS_BUSY_CODE: i32 = -32604;
```
I guess the two errors are customer server errors and the error codes should be one of the  `-32000 to -32099`?

**Comment by niklasad1** [comment]
Yupp, you are right.

Not sure, how we argued about that previously but let's change those within the -32000 to -32099 range.

**Comment by boundless-forest** [comment]
Fine. I would like to raise a pull request to adjust it.
