### ISSUE TITLE
Overriding name of parameter in param_kind=map for proc macro

### ISSUE THREAD

**Issue by allquixotic** [paritytech/jsonrpsee#1007]
Hi,

In my program which uses the jsonrpsee http client, I have a problem: my JSON-RPC server expects an input param with the name of, literally, `type`. Unfortunately, a variable cannot be named `type` in Rust because `type` is a language keyword.

See [here](https://github.com/allquixotic/encuum/blob/apps/src/applications.rs#L24) the open source code I'm working on with the problem. On line 24 here, I have to name the parameter `_type`, but that isn't what needs to be sent in the request: the request should send `type` as normal.

Is there a way to continue using the rpc proc macro with this naming convention for an input parameter, or do I need to use the client "late binding" (via serde_json::Value) and not benefit from the convenience of the proc macro?

The solution I envision would be something like specifying some kind of macro in front of the parameter that needs to be renamed. Like:

`#[custom_serial(name="type")]` (also would work with `name="fn"`, etc.) 

However, `#[serde(rename="something")]` is only for fields on structs from what I can tell...

**Comment by niklasad1** [comment]
Did you try `r#type: &String`?

Fair enough, would be nice to support it.

**Comment by allquixotic** [comment]
`r#type` doesn't work currently:

```
    #[method(name="Applications.getList", param_kind=map)]
    async fn get_applications_list(
        &self,
        session_id: &String,
        r#type: &String,
        page: Option<u32>,
        site_id: Option<u32>, //int|bool [optional]
        application_form_id: Option<u32>, //int|bool [optional]
        unread_only: Option<bool>,
        search: Option<String>,
        limit: Option<u32>,
    ) -> Result<GetApplicationsListResult, Error>;
```

```
2023-02-13T06:35:40.256243Z TRACE method_call{method="Applications.getList"}: jsonrpsee_core::tracing: send="{\"jsonrpc\":\"2.0\",\"id\":\"1\",\"method\":\"Applications.getList\",\"params\":{\"session_id\":\"redacted\",\"r#type\":\"open\",\"page\":1,\"site_id\":null,\"application_form_id\":null,\"unread_only\":null,\"search\":null,\"limit\":null}}"
```

comes back with:

```
2023-02-13T06:35:40.360391Z TRACE method_call{method="Applications.getList"}: jsonrpsee_core::tracing: recv="{\"error\":{\"code\":-32003,\"message\":\"Method is missing required parameter: type\"},\"id\":\"1\",\"jsonrpc\":\"2.0\"}"
```

**Comment by niklasad1** [comment]
ok, thanks for testing.

It shouldn't be that hard for us to parse raw identifiers i.e just strip `r#` from identifiers to fix that.

**Comment by allquixotic** [comment]
I'm in the midst of trying to implement this, as I need to get this done this month (it can't wait; the site I'm writing this tool to extract from is shutting down April 30). I'm trying to make my code as correct as possible to be able to contribute it upstream to jsonrpsee instead of maintaining my own fork...

How do you think this should be implemented from the user perspective?

Option 1: `#[method(param_name_map="r#type=type,some_other_param=some_other_mapped_value,param_three=map_three"]` where the values on the left hand side of the equals signs are the identifiers in the argument list of the method, and the right hand side values are the replacements.

Option 2: `#[method(param_name_arg1="foo", param_name_arg2="bar")]` where `arg1` and `arg2` are identifiers in the argument list of the method.

Or something else entirely?
