### ISSUE TITLE
server: expose RPC handler/JsonrpseeTowerService

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#1016]
Currently the server has its own `TowerService` which isn't exposed to external users which makes it not possible to fetch connection related details along with access to the JSON-RPC methods stuff.

Thus, the idea is to have a builder on or something similar which makes it possible to just get this JsonrpseeTowerService such that users can start their own hyper server without having to write tower middleware.

Such as

```rust
    // This API needs to be added
    let service = jsonrpsee::server::Builder::service();

   let wrapper_service = make_service_fn(move |conn: &AddrStream| {
       // write your logic here and utilize service
       
   });

   let listener = TcpListener::bind(&addr)?;

   loop {
        let (socket, _) = listener.accept().await?;
        tokio::spawn(try_accept_connection(socket, wrapper_service));
    }
```

**Comment by xlc** [comment]
This could be helpful. But how could we associate the connection details within the RpcModule handlers?

**Comment by niklasad1** [comment]
Yeah that's is a good question as the handler performs "the websocket upgrade" but we could remove that and some helper functions for that and the user can control that and manage that themselves by spawning a task or something.

However, I'm not convinced it may be better to just create a RpcModule and let the user manage it themselves.
