### ISSUE TITLE
JSON RPC notification

### ISSUE THREAD

**Issue by xlc** [paritytech/jsonrpsee#1017]
Not that I need this feature at all but reading the code makes me think the notification feature implementation isn't really correct.

Firstly, notifications are completely ignored (if handled). I don't see any interface exposed by jsonrpsee to allow subscription of notifications.

Secondly, the websocket server handles notifications inconsistently. For batch request, it will parse notifications and suppress responses. However, for single request, it simply error out with parse error, which I don't think is not spec confirming.

**Comment by niklasad1** [comment]
> Firstly, notifications are completely ignored (if handled). I don't see any interface exposed by jsonrpsee to allow subscription of notifications.

For the server, that is correct jsonrpsee only support ethereum pubsub.

> Secondly, the websocket server handles notifications inconsistently. For batch request, it will parse notifications and suppress responses. However, for single request, it simply error out with parse error, which I don't think is not spec confirming.

That's is not correct. 
For JSON-RPC notifications:
- HTTP server: just ACK the notification by send HTTP status code 200
- WS server: just ignore
- Batch response: just notifications are ignored.

Ok, I see I introduced a bug with some refactoring for the WS stuff.
