### ISSUE TITLE
Batch Requests

### ISSUE THREAD

**Issue by insipx** [paritytech/jsonrpsee#103]
I'm wondering about the plans to implement batch requests for the client. I saw a 'Batch' variant in the request enum, however, it seems like that's not being used in `RawClient` or  the `FrontToBack`/`request` method in client.rs is for singular requests. This is my first look at the code, but would it be correct to just add a `batch_request` method to add that logic/modify the enum variants and allow front-end batch-requests?

**Comment by niklasad1** [comment]
Yeah, you are correct because the serialize/deserialize is already in place for it, so it should be quite easy to implement at least in the client.

It just a matter of creating/designing a proper API for it, so I would say that it's planned to be supported.
