### ISSUE TITLE
Allow taking ownership of `ErrorObject` from `ErrorResponse`

### ISSUE THREAD

**Issue by prestwich** [paritytech/jsonrpsee#1042]
Feature request:

Client-side users of `ErrorResponse` typically don't need the ID or jsonrpc2.0 string. Allow the user to take ownership of the error object and drop the ID and 2.0 string

The current alternative is `err_resp.error_object().to_owned().into_owned()`, which is obviously bad code

```
impl ErrorResponse {
    // consume self, drop id and jsonrpc2.0, return only the object
    pub fn take_object(self) -> ErrorObject {
        self.error
    }
}
```

**Comment by niklasad1** [comment]
Make sense.

Not sure if we could have:

-  `as_error_object(&self) -> ErrorObject<'a>`
-  `into_error_object(self) -> ErrorObject<'static>`

**Comment by prestwich** [comment]
Cheers, thanks!
