### ISSUE TITLE
RPC `Response`: error while deserializing response for missing `jsonrpc` version field

### ISSUE THREAD

**Issue by gnapoli23** [paritytech/jsonrpsee#1045]
I was using the lib for interacting with a JSON-RPC server that does not provide the `jsonrpc` protocol version in its responses (actually it sets this field to `null`) and received an error in deserializing them.
Looking at sources, I saw that the `Response` struct defines the `jsonrpc` version field as required, while checking in the JSON-RPC 2.0 specification, this field is not mandatory but is actually optional.
Here the spec: [JSON-RPC 2.0 Spec](https://www.jsonrpc.org/specification#response_object)

**Comment by niklasad1** [comment]
Hey,

I agree with your interpretation as all other fields are marked as `REQUIRED` thus a request without that `"jsonrpc":"2.0"` is according to the spec.

But setting `"jsonrpc":null` is not according to the spec :)

**Comment by gnapoli23** [comment]
> Hey,
> 
> I agree with your interpretation as all other fields are marked as `REQUIRED` thus a request without that `"jsonrpc":"2.0"` is according to the spec.
> 
> > with a JSON-RPC server that does not provide the jsonrpc protocol version in its responses (actually it sets this field to null
> 
> `"jsonrpc":null` is not according to the spec,
> 
> > jsonrpc
> > A String specifying the version of the JSON-RPC protocol. MUST be exactly "2.0".

Yeah, correct, I meant "missing' :)
