### ISSUE TITLE
Number of permits exceeds limit on 32-bit platform

### ISSUE THREAD

**Issue by Aloxaf** [paritytech/jsonrpsee#1050]
https://github.com/paritytech/jsonrpsee/blob/014f7710e49d490adb79c4966912009058a6c5b8/core/src/server/rpc_module.rs#L469

According to tokio's docs. [Semaphore::MAX_PERMITS](https://docs.rs/tokio/1.26.0/tokio/sync/struct.Semaphore.html#associatedconstant.MAX_PERMITS) is `usize::MAX >> 3`. `u32::MAX` will cause panic on 32-bit platform.

**Comment by niklasad1** [comment]
Yes, nice catch it will be fixed once https://github.com/paritytech/jsonrpsee/pull/1034 is merged.
