### ISSUE TITLE
Can't stop gracefully multiple server instances in the same application

### ISSUE THREAD

**Issue by aoudiamoncef** [paritytech/jsonrpsee#1069]
Hello,

Currently, I'm working with `jsonrpsee` and I started 3 instances A B and C in the same application.

When I send a request to stop the application in A, we call `stop()` method in the three instances, but with actual implementation, B and C will never stop. We have to send additional requests to B and C to trigger the graceful shutdown.

To trigger a shutdown, we must create a connection to B and C to trigger the `stop_handle`. 

A simple `CTRL+C` will never trigger the graceful shutdown.

More detail https://github.com/massalabs/massa/issues/3759)

I'm waiting for feedback, if we could contribute upstream, we'll be happy to help. 

Thanks

**Comment by niklasad1** [comment]
@aoudiamoncef 

Which versions of tokio are you using? 
We noticed that tokio v1.27 broke our interval waker which was fixed recently https://github.com/paritytech/jsonrpsee/pull/1062 but we haven't made a new release yet.

If you can downgrade tokio to 1.26 that should fix it temporary I think.

**Comment by aoudiamoncef** [comment]
Hi,

We are using the last stable release of `jsonrpsee = 0.16.2` and `tokio = 1.23`

**Comment by niklasad1** [comment]
gotcha, something else then I suppose.

Can you elaborate what do you mean by "three instances"? Are these separate servers i.e, you call `Server::start` or something else?

**Comment by aoudiamoncef** [comment]
The problem is the fact that to trigger a graceful shutdown, we should send a request to trigger It. 

A simple `CTRL+C` can't kill properly the API and It keeps listening to the opened port. 

The workaround is OK, I'll send a query to stop my running API. But if I have multiples instances, I have to send n queries to stop each one.

**Comment by niklasad1** [comment]
We changed this recently on master to to handle connections tasks in tokio::spawn instead of the `FutureDriver` which may not be waken up until a new connection occurs. However, really weird that is works on server A but not on server B and C.

Thus, I think this is already fixed on master but could be wrong. Would be great if you could test it :pray:

**Comment by aoudiamoncef** [comment]
Hi @niklasad1 

I confirm that switching to [118acc3](https://github.com/paritytech/jsonrpsee/commit/118acc39668c60cd90174d91743c725f59275388) commit in master branch solves the issue. 

Thank you so much 👍🏻

**Comment by niklasad1** [comment]
Cool thanks for confirming, just be bare in mind that master has backpressure which may affect your connections, subscriptions and similar.

We will prep a new release soon

**Comment by niklasad1** [comment]
This is fixed by https://github.com/paritytech/jsonrpsee/pull/1080 and https://github.com/paritytech/jsonrpsee/pull/1062
