### ISSUE TITLE
HTTP background thread consumes 100% CPU

### ISSUE THREAD

**Issue by svyatonik** [paritytech/jsonrpsee#107]
The reason is that [`FuturesUnordered::poll_next()`](https://github.com/paritytech/jsonrpsee/blob/62da58d12321355aac76975bfedfbc3ab0fe08e3/src/transport/http/client.rs#L222) always returns `Poll::Ready(None)` if it is empty (at the start), or when all its futures have completed. So we instantly wake up [here](https://github.com/paritytech/jsonrpsee/blob/62da58d12321355aac76975bfedfbc3ab0fe08e3/src/transport/http/client.rs#L231) and proceed to the next iteration.

Bonus issue: it seems that completed futures are never removed from `pending_requests`.

**Comment by tomaka** [comment]
I haven't tested this, but it seems that something like that is much more elegant than #108

```diff
diff --git a/src/transport/http/client.rs b/src/transport/http/client.rs
index 96c854a..fb864e4 100644
--- a/src/transport/http/client.rs
+++ b/src/transport/http/client.rs
@@ -222,7 +222,19 @@ fn background_thread(mut requests_rx: mpsc::Receiver<FrontToBack>) {
         let mut pending_requests = stream::FuturesUnordered::new();
 
         loop {
-            let rq = match future::select(requests_rx.next(), pending_requests.next()).await {
+            let event = {
+                let next_pending_finished = async {
+                    if !pending_requests.is_empty() {
+                        pending_requests.next()
+                    } else {
+                        futures::pending!()
+                    }
+                };
+
+                future::select(requests_rx.next(), next_pending_finished).await
+            };
+
+            let rq = match event {
                 // We received a request from the foreground.
                 future::Either::Left((Some(rq), _)) => rq,
                 // The channel with the foreground has closed.
```

**Comment by svyatonik** [comment]
@tomaka You're right - thanks :) I've missed the fact that futures are actually removed from the `UnorderedFutures` when they are completed (so my 'bonus issue' looks invalid now :) ). Will prepare another PR, based on your solution.

**Comment by tomaka** [comment]
Again I haven't tested, but I think something like that should be quite elegant:

```rust
let event = loop {
    if !pending_requests.is_empty() {
        if let future::Either::Left(ev) = future::select(..., ...).await { break ev }; 
    } else {
        break requests_rx.next().await
    }
};

match event {
    ...
}
```
