### ISSUE TITLE
WsClient becomes unstable after heavy usage

### ISSUE THREAD

**Issue by liamaharon** [paritytech/jsonrpsee#1086]
As discussed in https://github.com/paritytech/substrate/pull/13923, the WsClient is unable to handle requesting all storage items (when the node is run in default configuration), but the HttpClient is able.

## Steps to reproduce

1. Checkout substrate branch [liam-soketto-error-reproduction](https://github.com/paritytech/substrate/tree/liam-soketto-error-reproduction)
2. Start a Kusama node on `ws://localhost:9944`
3. Run in `substrate`
```
RUST_LOG=debug cargo run --features=try-runtime try-runtime -lruntime=debug --runtime ../path/to/kusama/runtime-try-runtime on-runtime-upgrade live --uri ws://localhost:9944
```

During  processing, errors like this are logged and the WsClient appears to break: 
1. `ERROR tokio-runtime-worker jsonrpsee_core::client::async_client: [backend]: Invalid request ID`
2. `WARN tokio-runtime-worker soketto::connection: 8350acb7: accumulated message length exceeds maximum`
3. `ERROR tokio-runtime-worker jsonrpsee_core::client::async_client: [backend]: Networking or low-level protocol error: WebSocket connection error: message too large: len >= 10982657, maximum = 10485760` (even when sending a very small message)

Error 1 occurs most frequently when > 1 threads are used.
Errors 2,3 occur most frequently when 1 thread is used.
(you can change the number of threads used [here](https://github.com/paritytech/substrate/blob/4786a64863c3a5ad787537b2208a2f1d4fbdfb72/utils/frame/remote-externalities/src/lib.rs#L318))

These errors do not occur when an HttpClient is used in place of the WsClient, regardless of the number of threads used. When using HttpClient, when a 'request too large' message is received the request is broken up into smaller pieces and re-queried successfully.

**Comment by niklasad1** [comment]
I pushed a small fix to get the error cause to wrong branch and I got:

### public rpc node

```
2023-05-01 10:28:29.892 ERROR                 main remote-ext: Batch processing failed: "The background task been terminated because: Custom error: {\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32400,\"message\":\"Batch size limit exceeded.\"},\"id\":null}; restart required"   

```

### try runtime node
```bash
2023-05-01 10:42:24.159 ERROR                 main remote-ext: Batch processing failed: "The background task been terminated because: Networking or low-level protocol error: WebSocket connection error: message too large: len >= 145695926, maximum = 10485760; restart required"
```

So to me it looks like just the max_response_size needs to increased in the try-runtime as you can't know how big response the server will produce even with "a small batch request". I p

It could still be a an issue but can you retry with my small fix :)

**Comment by niklasad1** [comment]
### try runtime node with max limit

```bash
2023-05-01 11:14:31.423 DEBUG tokio-runtime-worker jsonrpsee_core::client::async_client: [backend]: Client dropped
2023-05-01 11:14:33.323  INFO                 main remote-ext: initialized state externalities with storage root 0xb37d962db2127e1a722c0b248f47c047b060307472c67d1e59d664c337c4bf5c and state_version V0    
Error: Input("given runtime is NOT compiled with try-runtime feature!")

```

**Comment by niklasad1** [comment]
After investigation this was caused:

1. `InvalidRequest` which was sent when the accumulated batch response was bigger than max limit on the server side
2. The format is: `{"jsonrpc": "2.0", "error": {"code": -32600, "message": "Invalid Request"}, "id": null}`
3. The client can't parse that `id` to a pending call and closes down the connection.
4. Any request after that is rejected and the client must create a new connection for that work again

So let's improve the error message but besides that everything works as intended.
