### ISSUE TITLE
Is it possible to build a JSON-RPC client/server via message queue?

### ISSUE THREAD

**Issue by tubzby** [paritytech/jsonrpsee#1110]
Like this [jsonrpc demo](https://github.com/paritytech/jsonrpc/blob/master/core/examples/async.rs).

The reason why a standard JSON-RPC server is not working in my case is that my server sits inside a local network, it only connects to the cloud via MQTT protocol.

I checked the source code *server/src/server.rs*, and it seems that *Server* is built upon a TCP connection, but I'm quite new here and might be missing something.

**Comment by niklasad1** [comment]
Yes, we have something similar which is called `RpcModule`  but sure it would probably good with an example for that in the examples folder.

Have a look here (we got examples in the rust docs):

- https://docs.rs/jsonrpsee-core/latest/jsonrpsee_core/server/struct.RpcModule.html#method.call
- https://docs.rs/jsonrpsee-core/latest/jsonrpsee_core/server/struct.RpcModule.html#method.raw_json_request
- https://docs.rs/jsonrpsee-core/latest/jsonrpsee_core/server/struct.RpcModule.html#method.subscribe_unbounded
