### ISSUE TITLE
Feature Request: have `jsonrpsee::server::logger` return result as RpcResult instead of a string?

### ISSUE THREAD

**Issue by wlmyng** [paritytech/jsonrpsee#1129]
I have some prometheus metrics set up on a logger that implements `jsonrpsee::server::logger`. All errors currently increment a single `errors_by_route` metric, but now I'd like to increment different error metrics depending on the response error code. However, the logger only provides a `success: bool` from `on_result`, or a `result: &str` from `on_response`. Could we have `on_response` return the actual RpcResult instead?

**Comment by niklasad1** [comment]
I like the idea but it's not trivial to implement because each rpc method just returns `IntoResponse/String` and the server itself doesn't know the error code etc when logging the response.

**Comment by wlmyng** [comment]
Thanks for reviewing! Fired off the first comment without looking into deeper. Having reviewed the code a bit more, what about the following? 

We can extend `MethodResponse` and the corresponding batch one to hold an optional new field `error_object`(s). 
https://github.com/paritytech/jsonrpsee/blob/7b43500124e9685af5bb930e344d9ac17d8dd347/core/src/server/helpers.rs#L227
Is it possible to then pass this as a param to the logger instead of the string result? https://github.com/paritytech/jsonrpsee/blob/master/server/src/transport/http.rs#L95

**Comment by wlmyng** [comment]
Maybe something like this? https://github.com/wlmyng/jsonrpsee/pull/2 At least for my purposes I only really just need to expose the error code

**Comment by wlmyng** [comment]
correspondingly on v0.18.2 https://github.com/wlmyng/jsonrpsee/pull/2

**Comment by niklasad1** [comment]
Hey @wlmyng 

This change doesn't make sense because the introduced `IntoResponse/ResponsePayload` is managing the error code so for you idea to work I think the `Logger` has to be injected into the RpcModule for that work.

You will end up with internal error codes emitted by jsonrpsee only and not user defined ones :(

**Comment by wlmyng** [comment]
Ah I see, we're still on `v0.16.2` so I didn't really follow until your latest message + trying it out for myself. Hmm...

In the meantime then, do you have any recommendations for alternative approaches?

**Comment by niklasad1** [comment]
I need to look at the code more closely but yeah it may not be possible to implement without a huge refactoring :(

**Comment by wlmyng** [comment]
What I've noticed is that on v0.16.2, when I print the `response` in https://github.com/paritytech/jsonrpsee/blob/v0.16.2/server/src/transport/http.rs#L223, I see the following (each line is an individual example):
```
MethodResponse { result: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32602,\"message\":\"No more params\"},\"id\":5}", success: false }
MethodResponse { result: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-12345,\"message\":\"hello received\"},\"id\":6}", success: false }
MethodResponse { result: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-54321,\"message\":\"c\"},\"id\":7}", success: false }
```

So the `success` param for `on_result` in the logger corresponds to whether the client would receive a success or error response. Can verify here: https://github.com/wlmyng/jsonrpsee/pull/3

Now in `v0.18.2`, this is no longer the case. For example, this is what I see for `MethodResponse`:
`MethodResponse { result: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32602,\"message\":\"Invalid params\",\"data\":\"No more params\"},\"id\":5}", success: true }
MethodResponse { result: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-12345,\"message\":\"hello received\"},\"id\":6}", success: true }
MethodResponse { result: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-54321,\"message\":\"c\"},\"id\":7}", success: true }`. Can verify here: https://github.com/wlmyng/jsonrpsee/pull/4

Is this a symptom of the breaking change? Based on v0.16.2, I thought that the logger's `on_result` `success` param corresponded to whether the jsonrpc method yields a `result` or `error`. But it looks like now, at least for `v0.18.2`, `success` instead corresponds to whether jsonrpc was able to return a result at all. Could you please inform on what `success` should correspond to?

I'm not quite sure what caused this difference, but I've located the code pointer that would support my use case on `v0.18.2`:
```rust
pub fn response<T>(id: Id, result: ResponsePayload<T>, max_response_size: usize) -> Self
	where
		T: Serialize + Clone,
	{
		let mut writer = BoundedWriter::new(max_response_size);

		match serde_json::to_writer(&mut writer, &Response::new(result, id.clone())) {
			Ok(_) => {
				// Safety - serde_json does not emit invalid UTF-8.
				let result = unsafe { String::from_utf8_unchecked(writer.into_bytes()) };
				Self { result, success: true, error_code: None }
			}
```

I think it should be p straightforward to extend this:
```rust
	pub fn response<T>(id: Id, result: ResponsePayload<T>, max_response_size: usize) -> Self
	where
		T: Serialize + Clone,
	{
		let mut writer = BoundedWriter::new(max_response_size);
		let response = Response::new(result, id.clone());

		match serde_json::to_writer(&mut writer, &response) {
			Ok(_) => {
				// Safety - serde_json does not emit invalid UTF-8.
				let result = unsafe { String::from_utf8_unchecked(writer.into_bytes()) };
				let error_code = if let ResponsePayload::Error(e) = &response.payload {
					Some(e.code())
				} else {
					None
				};
		
				Self { result, success: true, error_code }
			}
```

And now I'm able to see:
```rust
MethodResponse { result: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32602,\"message\":\"Invalid params\",\"data\":\"No more params\"},\"id\":5}", success: true, error_code: Some(-32602) }
MethodResponse { result: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-12345,\"message\":\"hello received\"},\"id\":6}", success: true, error_code: Some(-12345) }
MethodResponse { result: "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-54321,\"message\":\"c\"},\"id\":7}", success: true, error_code: Some(-54321) }
```

Do you have any reservations about this?

**Comment by niklasad1** [comment]
> Is this a symptom of the breaking change? Based on v0.16.2, I thought that the logger's on_result success param corresponded to whether the jsonrpc method yields a result or error. But it looks like now, at least for v0.18.2, success instead corresponds to whether jsonrpc was able to return a result at all. Could you please inform on what success should correspond to?

Is it a bug indeed, the success field should indicate whether the RPC call was successful or not.

> Do you have any reservations about this?

I'm not super excited about having `error code` in the MethodResponse but I don't see a better way to support it.
