### ISSUE TITLE
How to specify optional array arguments 

### ISSUE THREAD

**Issue by NicolasPennie** [paritytech/jsonrpsee#1140]
Hi – Is it possible with jsonrpsee to specify optional fields? 

For example, say I have the following arguments:
```
pub struct RequestExample {
    pub foo: String,
    pub bar: Option<String>,
}
```

This request will work:
```
{
  "jsonrpc": "2.0",
  "id": "0",
  "method": "request_example",
  "params":  {
     "foo": "works"
  }
}
```

But this request will fail:
```
{
  "jsonrpc": "2.0",
  "id": "0",
  "method": "request_example",
  "params":  [
     "doesNotWork"
   ]
}
```

**Comment by niklasad1** [comment]
Hey, 

JSON-RPC allows the params to be passed as array or object:

1. array: ```{"jsonrpc": "2.0", "id": "0", "method": "request_example", "params":["foo"]}```
2. map/object: ```{"jsonrpc": "2.0", "id": "0", "method": "request_example", "params":{"foo": works}}```

It's possible to allow optional parameters in jsonrpsee but if you want to use `RequestExample`as params then it's serialized as JSON map/object andit becomes `[{"foo": String, "bar": null}]` which won't work if you pass the params as an `array` unless you implement some custom serialize impl.
 
The easiest would be to remove the struct RequestExample and just use `async fn request(foo: String, bar: Option<String>)`
then it should work to pass it as an array and object.
