### ISSUE TITLE
How can I access the request id of an incoming request?

### ISSUE THREAD

**Issue by binarybaron** [paritytech/jsonrpsee#1190]
Is it possible to access the request id within the callback that is supplied to register_async_function?

**Comment by niklasad1** [comment]
Hey @binarybaron 

No, unfortunately not the callback exposes the params in the JSON-RPC method call and the context in the RpcModule. 
Can you explain why you need it?

**Comment by binarybaron** [comment]
I want to add context (using tracing spans) to the log messages that are printed as a result of a RPC call.
