### ISSUE TITLE
How to get disconnect reason?

### ISSUE THREAD

**Issue by xlc** [paritytech/jsonrpsee#1196]
I am using `on_disconnect` to get notified on disconnect and retry connection.

https://github.com/paritytech/jsonrpsee/blob/d4ea3464dc9866fac1ec284e65090b52015e10b6/core/src/client/async_client/mod.rs#L320

But how can I get disconnect reason so that I can implement advanced retry strategy?

**Comment by niklasad1** [comment]
There is no dedicated API to get the disconnect reason but we can add it sure.

As a workaround you can make a dummy request to get close reason by `Error::RestartNeeded(String)` but I think 
you would need a typed error for that and maybe we can make that error type clone/Arc<Error> instead.

**Comment by xlc** [comment]
Can we update the on_disconnected to have it return the error reason?

**Comment by niklasad1** [comment]
If it's possible to ensure that it's still is cancel-safe sure
