### ISSUE TITLE
Is there any way to let go jsonrpc client to call jsonrpsee server?

### ISSUE THREAD

**Issue by Cassuis** [paritytech/jsonrpsee#1199]
Is there any way to let go jsonrpc client to call jsonrpsee server?

**Comment by niklasad1** [comment]
Hey @Cassuis 

Can you elaborate what you mean with example code or something with more well described?

I guess you want to use the client from [jsonrpc crate](https://github.com/paritytech/jsonrpc) to call the jsonrpsee server? Sure that should work but I'm not following what you want to do....

**Comment by Cassuis** [comment]
> Hey @Cassuis
> 
> Can you elaborate what you mean with example code or something similar?
> 
> I guess you want to use the client from [jsonrpc crate](https://github.com/paritytech/jsonrpc) to call the jsonrpsee server? Sure that should work but I'm not following what you want to do....

sorry,my bad,i mean use golang to init a rpc client to call jsonrpsee rpc server

**Comment by lexnv** [comment]
Hey

I do believe you could spawn a jsonrpsee rust server in one process, then use any golang rpc clients to communicate with it.

The RPC server does obey to the [json-rpc spec](https://www.jsonrpc.org/specification), and as long as the golang client does the same, your connection should work properly.

If you could share a bit more details, it would help us understand this better:
- Do you have a specific use-case in mind? (ie why not golang server)
- Which golang rpc client are you planning to use? 

Super cool thing to try out, let us know if that works for you! 🙏

**Comment by Cassuis** [comment]
> Hey
> 
> I do believe you could spawn a jsonrpsee rust server in one process, then use any golang rpc clients to communicate with it.
> 
> The RPC server does obey to the [json-rpc spec](https://www.jsonrpc.org/specification), and as long as the golang client does the same, your connection should work properly.
> 
> If you could share a bit more details, it would help us understand this better:
> 
> * Do you have a specific use-case in mind? (ie why not golang server)
> * Which golang rpc client are you planning to use?
> 
> Super cool thing to try out, let us know if that works for you! 🙏

i will try it first,I'll call you if there's any trouble !~ my golang rpc server/client is jsonrpc1.0,i need to upgrade it first.

**Comment by Cassuis** [comment]
1. Do you have a specific use-case in mind? (ie why not golang server)
    Cuz i want to rewirte my golang rpc server in rust,but the upstream invocation service(rpc-client) write by golang.
2. Which golang rpc client are you planning to use?
    Cuze jsonrpsee obey to the json-rpc spec 2.0,so i need to search which golang rcp client lib can support json-rpc spec 2.0

**Comment by Cassuis** [comment]
> Hey
> 
> I do believe you could spawn a jsonrpsee rust server in one process, then use any golang rpc clients to communicate with it.
> 
> The RPC server does obey to the [json-rpc spec](https://www.jsonrpc.org/specification), and as long as the golang client does the same, your connection should work properly.
> 
> If you could share a bit more details, it would help us understand this better:
> 
> * Do you have a specific use-case in mind? (ie why not golang server)
> * Which golang rpc client are you planning to use?
> 
> Super cool thing to try out, let us know if that works for you! 🙏

i found a jsonrpc lib with golang,here is  demo for server,and i want to known how to write ws server with jsonrpsee


`type SimpleServerHandler struct {
    n int
}

func (h *SimpleServerHandler) AddGet(in int) int {
    h.n += in
    return h.n
}

func main() {
    // create a new server instance
    rpcServer := jsonrpc.NewServer()
    
    // create a handler instance and register it
    serverHandler := &SimpleServerHandler{}
    rpcServer.Register("SimpleServerHandler", serverHandler)
    
    // rpcServer is now http.Handler which will serve jsonrpc calls to SimpleServerHandler.AddGet
    // a method with a single int param, and an int response. The server supports both http and websockets.
    
    // serve the api
    testServ := httptest.NewServer(rpcServer)
    defer testServ.Close()
	
    fmt.Println("URL: ", "ws://"+testServ.Listener.Addr().String())
    
    [..do other app stuff / wait..]
}`

**Comment by niklasad1** [comment]
@Cassuis 

[have look at this example](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/ws.rs) but the jsonrpsee server already supports HTTP and WebSocket by default on the same port. You only need the `run_server` part 

I'm going to close this issue and I encourage you to add a discussion topic for this if you need more help
