### ISSUE TITLE
Lots of idle connection on HTTP RPC server.

### ISSUE THREAD

**Issue by tubzby** [paritytech/jsonrpsee#1202]
I'm running a JSON RPC server: 

```rust
    pub async fn listen(&self, port: u16) -> anyhow::Result<()> {
        info!("listening at: {port}");

        let server = ServerBuilder::default()
            .build(format!("0.0.0.0:{port}"))
            .await?;
        let handle = server.start(self.rpc.clone());
        tokio::spawn(handle.stopped());
        Ok(())
    }

```

After some time the server stops serving and returns HTTP status 429 to the client, I have checked the socket on the server using `netstat -an` and found out that over 100 `ESTABLISHED` connections were made, seems that the server is not closing the idle connection.

I have tried：
1. `build_from_tcp` with `socket2` with `TcpKeepAlive` enabled on the server.
2. Setting ping_interval.

and failed.

**Comment by niklasad1** [comment]
Thanks for the report.

Are you sure that is really happening on a JSON-RPC HTTP requests and not on Websocket? To be sure you could call https://docs.rs/jsonrpsee-server/latest/jsonrpsee_server/struct.ServerBuilder.html#method.http_only on your server.

Any trivial way reproduce this locally?
Lastly can you report which version of jsonrpsee your are using?

**Comment by tubzby** [comment]
1. I assume the following client code is using HTTP not WebSocket:
```rust
    let client = HttpClientBuilder::default()
        .request_timeout(Duration::from_secs(1))
        .build(URL)
        .unwrap();

```

2. I'm using version `0.20.0`

3. I'm testing the JSON RPC server with a client that just `telnet` to the server port without sending anything, and then unplugs the ether cable that will leave a idle connection on the server side.

**Comment by niklasad1** [comment]
Are you using the loopback address when unplugging the ethernet cable?
The loopback interface will work even if you unplug the ethernet cable...

This is library is using the hyper HTTP server I would be very surprised if this occurs on a "real network" but happy to be proven wrong :)

**Comment by tubzby** [comment]
I'm running the server on my Mac and a `telnet` on Windows.

I tested your code on Ubuntu Linux and I can confirm TCP keepalive is working by  `tcpdump`, but a little bit confusing on MacOS:

* The server is listening at the port
* When a client `telnet` to the port, it fails, and then `netstat` shows that the port is no longer listening.

Thank you for your help!

**Comment by niklasad1** [comment]
I don't see any other fix jsonrpsee can provide and closing this one.

Please re-open if you don't agree.
