### ISSUE TITLE
Renaming Function Parameters for Client API

### ISSUE THREAD

**Issue by nannick** [paritytech/jsonrpsee#121]
I am trying to create a client that interacts with a server, however I am running into a small issue when attempting to send a request.  Specifically, the params are not being serialized the correct way.

Currently a valid serialization of the params would look like this : 
 "params" : [{"/":"bafy2bzacea3wsdh6y3a36tb3skempjoxqpuyompjbmfeyf34fi3uy6uue42v4"}]

However the request that is being sent has a  params field that looks like this : 
"params":{"params":"bafy2bzacecujyfvb74s7xxnlajidxpgcpk6abyatk62dlhgq6gcob3iixhgom"}

Currently my client API is defined as :

![a](https://user-images.githubusercontent.com/18388850/88485673-a1a72400-cf45-11ea-853a-294d078a0199.png)

I understand that the reason the request is incorrect is because it is using "params" instead of "/". However I am not sure how to fix the issue. Is there a way to rename the method parameter so when it is serialized, it uses "/" instead of "params" or is there a much more simple solution?

**Comment by austinabell** [comment]
You want to use the positional params config option, such as: `#[rpc(method = "...", positional_params)]` (the object with `/` key is just a project specific thing if that is confusing to a reader)

Is there any docs on this? I just saw through examples, but knowing which config options are available would be nice

**Comment by nannick** [comment]
> You want to use the positional params config option, such as: `#[rpc(method = "...", positional_params)]` (the object with `/` key is just a project specific thing if that is confusing to a reader)
> 
> Is there any docs on this? I just saw through examples, but knowing which config options are available would be nice

The above solved my issue.
