### ISSUE TITLE
Bad behavior when decoding server response fails

### ISSUE THREAD

**Issue by DemiMarie** [paritytech/jsonrpsee#124]
When decoding the server response fails due to the server response missing required fields, `jsonrpsee` seems to behave weirdly.  Typically, it will hang for an indeterminate amount of time.

**Comment by niklasad1** [comment]
Ok, the failed server response has nothing to do with that the `fmt::debug impl` for  [Params::Array](https://github.com/paritytech/jsonrpsee/blob/master/src/raw/server/params.rs#L89) is missing? 

Would be good if you could write down which specific action that triggers a server response with missing fields.

**Comment by niklasad1** [comment]
If the `jsonrpc` deserialization fails the entire connection is dropped on `master`, it is fixed on `v2` with the following change: https://github.com/paritytech/jsonrpsee/blob/v2/src/ws/transport.rs#L386-#L411

**Comment by niklasad1** [comment]
Closing as stale, because the servers have changed significantly since reporting this issue.
