### ISSUE TITLE
How to send an empty params body (not omit it)

### ISSUE THREAD

**Issue by khumps** [paritytech/jsonrpsee#1278]
Zabbix requires the params body always be there even when it is empty. For example, the following curl is in their docs to retrieve the API version

```
curl --request POST \
  --url 'https://example.com/zabbix/api_jsonrpc.php' \
  --header 'Content-Type: application/json-rpc' \
  --data '{"jsonrpc":"2.0","method":"apiinfo.version","params":{},"id":1}'
  ```

I can't seem to find a way to replicate this behavior. This doesn't seem to do it, it just omits the params object entirely
```rust
let client = HttpClientBuilder::default().build("https://example.com/zabbix/api_jsonrpc.php")?;

    let resp = client
        .request("apiinfo.version", rpc_params!())
        .await?;
```

According to the JSON-RPC spec
> params
A Structured value that holds the parameter values to be used during the invocation of the method. This member MAY be omitted.

Which suggests their API isn't to spec (so maybe this isn't something the library intends to support)

**Comment by niklasad1** [comment]
Hey @khumps 

As you noticed the `rpc_params!` and the other params implementation will omit the params if it's empty but you can implement your own type where you can provide the serialized result:

```rust
struct EmptyParams;

impl ToRpcParams for EmptyParams {
    fn to_rpc_params(self) -> Result<Option<Box<RawValue>>, serde_json::Error> {
        Ok(Some(serde_json::value::to_raw_value("{}").unwrap()))
    }
}

let client = HttpClientBuilder::default().build("https://example.com/zabbix/api_jsonrpc.php")?;
let resp = client.request("say_hello", EmptyParams).await?;
```

**Comment by khumps** [comment]
> Hey @khumps
> 
> As you noticed the `rpc_params!` and the other params implementation will omit the params if it's empty but you can provide your own type that implements `ToRpcParams` where you can provide the serialized result:
> 
> ```rust
> struct EmptyParams;
> 
> impl ToRpcParams for EmptyParams {
>     fn to_rpc_params(self) -> Result<Option<Box<RawValue>>, serde_json::Error> {
>         Ok(Some(serde_json::value::to_raw_value("{}").unwrap()))
>     }
> }
> 
> let client = HttpClientBuilder::default().build("https://example.com/zabbix/api_jsonrpc.php")?;
> let resp = client.request("apiinfo.version", EmptyParams).await?;
> ```

I tried that but I think the API specifically wants an object `{}` not a string `"{}"`. I was able to use the code you provided and instead serialize an empty hashmap to get the result

```rust
impl ToRpcParams for EmptyRpcParams {
    fn to_rpc_params(self) -> Result<Option<Box<RawValue>>, serde_json::Error> {
        Ok(Some(serde_json::value::to_raw_value(&HashMap::<String, String>::new()).unwrap()))
    }
}
```
