### ISSUE TITLE
AtomicU64/AtomicI64 is no longer supported by the *-espidf targets.

### ISSUE THREAD

**Issue by blue-freedom-technologies** [paritytech/jsonrpsee#1290]
AtomicU64/AtomicI64 is no longer supported by the *-espidf targets. [Refer to the changelog for version 0.42.4 of esp-idf-hal](https://github.com/esp-rs/esp-idf-hal/blob/81675ccbf5d6868fedb3fa19a57d84ee5cfc06b0/CHANGELOG.md?plain=1#L28C1-L29C99)

Which is my case I am using a ESP32-C6 target = "riscv32imac-esp-espidf"

Error:

```text
error[E0432]: unresolved import `std::sync::atomic::AtomicU64`
  --> /home/ei02008/.cargo/registry/src/index.crates.io-6f17d22bba15001f/jsonrpsee-core-0.21.0/src/client/mod.rs:40:25
   |
40 | use std::sync::atomic::{AtomicU64, Ordering};
   |                         ^^^^^^^^^
   |                         |
   |                         no `AtomicU64` in `sync::atomic`
   |                         help: a similar name exists in the module: `AtomicU32`
```

Would be nice to have this fixed.

Cheers,

**Comment by niklasad1** [comment]
We can probably migrate to `AtomicUsize`, that would fix it right?

**Comment by blue-freedom-technologies** [comment]
Hi @niklasad1 ,

yes,

both AtomicUsize and AtomicU32 worked for our target = "riscv32imac-esp-espidf".

This is our [patch](https://github.com/blue-freedom-technologies/jsonrpsee/commit/4b1aaca4e255fd8e15f004718e0a15aa132d08d6) based in the jsonrpsee fork.

Cheers,
