### ISSUE TITLE
[ws server]: should reply `parse_error` when deserialization fails

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#130]
The server should reply with `-32700 Parse error` when the deserialization fails, see https://github.com/paritytech/jsonrpsee/blob/master/src/transport/ws/server.rs#L339-#L342

**Comment by tomusdrw** [comment]
The problem with this is that you need to at least extract the `id` of the call for the response to make any sense (in WS the user can't match request with a response in any other way). We do it like this in `jsonrpc`:
https://github.com/paritytech/jsonrpc/blob/master/core/src/types/request.rs#L49

**Comment by niklasad1** [comment]
Thanks, got it. In the `v2` branch I just returned `Id == Null`  when the deserialization failed but after reading:

> If there was an error in detecting the id in the Request object (e.g. Parse error/Invalid Request), it MUST be Null.

Your way is correct and according to the spec.

**Comment by niklasad1** [comment]
Fixed by #180
