### ISSUE TITLE
Stdio support for subprocess communication

### ISSUE THREAD

**Issue by acolombier** [paritytech/jsonrpsee#1309]
Hi,

This request is the same this one on [paritytech/jsonrpc](https://github.com/paritytech/jsonrpc/issues/489). Is that something that can already be done with the current state? If yes, do you have any pointer or example which can be used to get something implemented? I'm looking for the same solution than detailed in the above issue - a server with register command and interfaces/types, ran in the parent process, a client interacting also registering command and running as a sub-process

**Comment by niklasad1** [comment]
Hello @acolombier 

We have no server/client implementation that supports stdio and no intention to support it at the moment.
What you can do is to implement "stdio transport" yourself for the jsonrpsee client and then use the stdio jsonrpc server from the legacy crate.

You use the following template for it the client code but I don't know whether there is a good crate that wrap stdin/stdout in that supports tokio v1.0:

```rust
use std::io::{Read, Write};

use jsonrpsee::core::async_trait;
use jsonrpsee::core::client::{
	Client, ClientBuilder, ClientT, Error, ReceivedMessage, TransportReceiverT, TransportSenderT,
};
use jsonrpsee::rpc_params;

struct Sender(tokio_stdin_stdout::ThreadedStdout);

#[async_trait]
impl TransportSenderT for Sender {
	type Error = Error;

	async fn send(&mut self, msg: String) -> Result<(), Self::Error> {
		// TODO: use async write and don't unwrap
		let _n = self.0.write(msg.as_bytes()).unwrap();

		Ok(())
	}
}

struct Receiver(tokio_stdin_stdout::ThreadedStdin);

#[async_trait]
impl TransportReceiverT for Receiver {
	type Error = Error;

	async fn receive(&mut self) -> Result<ReceivedMessage, Self::Error> {
		let mut buf = Vec::new();
		// TODO: use async read and don't unwrap
		let _n = self.0.read(&mut buf).unwrap();

		Ok(ReceivedMessage::Bytes(buf))
	}
}

fn stdio_transport(sender: tokio_stdin_stdout::ThreadedStdout, receiver: tokio_stdin_stdout::ThreadedStdin) -> (Sender, Receiver) {
	let sender = Sender(sender);
	let receiver = Receiver(receiver);
	(sender, receiver)
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
	// start server
	// share stdio/stdout here
	let (tx, rx) = stdio_transport(stdin, stdout);

	let client: Client = ClientBuilder::default().build_with_tokio(tx, rx);
	let response: String = client.request("say_hello", rpc_params![]).await?;
	tracing::info!("response: {:?}", response);
```

**Comment by orowith2os** [comment]
What's the reasoning behind jsonrpsee not wanting to support stdio? I get that it's easy enough to implement, but it would be helpful (and appears to be fairly simple to support in the main crate?), especially for me, who wants a simple client-server architecture (but only supporting one client).
