### ISSUE TITLE
Automatic documentation

### ISSUE THREAD

**Issue by pmantica11** [paritytech/jsonrpsee#1317]
First. thank you so much for this amazing project!

Jsonrpsee works great and we have been using it in production. I was wondering if there was any way to generate automatic documentation for the APIs/SDKs? This would be incredibly helpful!

**Comment by niklasad1** [comment]
Hey @pmantica11 thanks.

You want something similar to https://github.com/paritytech/jsonrpsee/issues/737 correct?

**Comment by pmantica11** [comment]
Yep! That would work! Closing this one since it's a bit of a duplicate.
