### ISSUE TITLE
Lower the logging level

### ISSUE THREAD

**Issue by dpc** [paritytech/jsonrpsee#1329]
In a bigger applications jsonrpc errors like connection issues are never really big high level errors requiring user attention, but implementation details that most probably will be retried or ignored anyway. For this reason, I think jsonrpsee, especially the client part should only ever use `trace!` and `debug!` logging levels. Especially `error!` should be avoided. Otherwise user code is forced to just unconditionally add `jsonrpsee-client=off` to `RUST_LOG`.

**Comment by niklasad1** [comment]
Sure, that's fair we can downgrade those to debug/trace.

I think we already did it for the server IIRC.
