### ISSUE TITLE
Hanging on read next message

### ISSUE THREAD

**Issue by de-ltd** [paritytech/jsonrpsee#1344]
I seem to be having an issue with a service provider I am streaming data from.

My software connects and subscribes with their endpoint fine, and works for a while. The problem is after x minutes it will hang on .next().await and not produce any errors ect.

My service provider's system shows me that the websocket disconnects, but my software will hang on waiting for the next message for sometimes 30 minutes - 1 hour before detecting that the WS has closed so it can therefore be handled and reconnected.

I am using jsonrpsee v0.20.3 due to compat issues with other crates, and I am building the websocket using a ping_interval of 5 seconds - rest of the settings are default.

Does anyone have any idea if this could be something my side or is it them not handling things correctly?

**Comment by niklasad1** [comment]
Hey hey,

From my understanding is that you are using the jsonrpsee_ws_client, create a subscription then when you are waiting for the next message it doesn't return/indicates that connection has been closed when it occurs?

The easiest way to investigate what is going is to enable trace logs `RUST_LOG=trace=jsonpsee,trace=soketto,info"`, my guess is that server/service you are using isn't doing a proper websocket close handshake.

Just a headsup that WS client ping/pong API is improved in v0.21 and you can decide the close the connection if you don't get any ACK back in "time", https://docs.rs/jsonrpsee-ws-client/latest/jsonrpsee_ws_client/struct.PingConfig.html which you can use to workaround your issue.

However, would be good to know whether this a bug on our side or not

**Comment by de-ltd** [comment]
> Hey hey,
> 
> From my understanding is that you are using the jsonrpsee_ws_client, create a subscription and then when you are waiting for the next message it doesn't return/indicates that connection has been closed when it occurs?
> 
> The easiest way to investigate what is going is to enable trace logs `RUST_LOG=trace=jsonpsee,trace=soketto,info"`, my guess is that server/service you are using isn't doing a proper websocket close handshake/or really closes down the connection.
> 
> Just a headsup that WS client ping/pong API is improved in v0.21 and you can decide the close the connection if you don't get any ACK back in "time", https://docs.rs/jsonrpsee-ws-client/latest/jsonrpsee_ws_client/struct.PingConfig.html which you can use to workaround your issue.
> 
> However, would be good to know whether this a bug on our side or not

I will check both of those things out thank you!
