### ISSUE TITLE
Tracking WS/Http specific request metrics

### ISSUE THREAD

**Issue by mattsse** [paritytech/jsonrpsee#1345]
with a `RpcServiceT` metrics for requests can be easily collected, before 0.21 this could be done via the Logger trait.

with `RpcServiceT` we don't know the transport (ws/http), so it's not possible to track ws/http specific request metrics if the server has both HTTP and WS enabled, for example number of ws/https calls/connections.

The transport could be obtained via a `HttpMiddleware` that checks the incoming HTTP request, just as jsonrpsee does (`is_upgrade_request`). 
But I couldn't figure out how to pass that information to the `rpc_middleware`.

perhaps it's beneficial to include that context (`TransportProtocol`) in the `RpcServiceT` trait. I assume this could even be added in a non breaking way by a new function to the `RpcServiceT`, like either `set_transport` or as an additional `call` function with an additional argument that by default delegates to `RpcServiceT::call`

**Comment by niklasad1** [comment]
Hey hey,

We tried to explain in the changelog that you must use the low-level server API that we introduced in v0.21 to implement such metrics where you need to select yourself what kind of data to wrap in your middleware type such that you may want some special HTTP header, ip addr etc. So it's a bit more annoying to implement now but that's tradeoff right now.

You can find an example how to do it [here](https://github.com/paritytech/polkadot-sdk/blob/master/substrate/client/rpc-servers/src/lib.rs#L100-#L229)

We can probably add an example in jsonrpsee to make this more obvious as well...

**Comment by mattsse** [comment]
gotcha!

ty, this is helpful.
