### ISSUE TITLE
[Feature Rqeuest]: Generate documentation from traits declarations and attrs of `#[rpc]` macro

### ISSUE THREAD

**Issue by Velnbur** [paritytech/jsonrpsee#1348]
Problem
---

There is a such thing as [`okapi`](https://docs.rs/crate/rocket_okapi/latest) which generates a documentation file by OpenAPI (swagger) spec from the usage of `#[route]` macro.

Possible solution
---

With gathered by `#[rpc]` macro attributes and doc-comments, insert markdown-formatted text into some buffer, and then at the end of the compilation create an output file with gathered data.

Consideration
---

For a reference, you may check out [Bitcoin RPC](https://developer.bitcoin.org/reference/rpc/) and [Ethereum RPC](https://ethereum.org/en/developers/docs/apis/json-rpc/) docs which could be a great example how to structure the doc.

For example, we have trait declarations like this:

```rust
#[rpc(server)]
#[group = "Books"]
pub trait BooksRpc {
    /// Fetch the book by id
    ///
    /// ### Parameters
    /// 
    /// * `id` - id of the book
    ///
    /// ### Returns
    /// 
    /// Serialized book
    #[method(name = "getbook")]
    async fn get_book(id: u32) -> RpcResult<Book>;
}
```

Which will generate doc like this:

---
# JSON RPC API Specification

> some kind of TOC here

### `getbook`

Fetch the book by id

### Parameters

* `id` - id of the book

### Returns

Book

### Example

> May be even generate an example for curl:

```shell
// Request
curl -X POST --data '{"jsonrpc":"2.0","method":"getbook","params":[1],"id":1}'
// Result
{
  "id":67,
  "jsonrpc":"2.0",
  "result": {
    "data": ...,
  },
}
```

> But the problem is how to get default values for parameters and response..., may be as for **Parameters** and **Returns** leave that to user

---

**Comment by niklasad1** [comment]
It's really a neat idea but because jsonrpsee supports generic types/custom types in the API then how to determine what the serialized format is such as String, number etc?

I think it's similar to https://github.com/paritytech/jsonrpsee/issues/737 but again would be neat for sure

**Comment by Velnbur** [comment]
Yeah, I missed that as well as the author did in #1317. `OpenRPC` is great, I'll move the discussion in #737
