### ISSUE TITLE
[server]: `unsubscribe_call` doesn't close subscriptions as intended

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#135]
When an `unsubscription call` is received by the [Server](https://github.com/paritytech/jsonrpsee/blob/master/src/server.rs#L458) then `RawServerSubscriptionId::from_wire_message` tries to parse it from `hardcoded JsonValue::Null` where the `subscription ID` should be parsed instead. Thus, RawServerSubscriptionId::from_wire_message always fails to parse the subscription ID

This causes dropping a `registered subscription` not work with one exception when the entire client is dropped then it works via [SubscriptionsClosed](https://github.com/paritytech/jsonrpsee/blob/master/src/server.rs#L482-#L493)

**Comment by dvdplm** [comment]
Maybe unrelated but I think [`null` is a valid JSON document](https://stackoverflow.com/questions/8526995/is-null-valid-json-4-bytes-nothing-else).

**Comment by niklasad1** [comment]
Yeah, it is unrelated the problem is that `JsonValue::Null` is hardcoded instead the `subscription ID` should be parsed. I rephrased the description hopefully more understandable now

**Comment by niklasad1** [comment]
Fixed by #180
