### ISSUE TITLE
Username and password in the url ignored

### ISSUE THREAD

**Issue by dpc** [paritytech/jsonrpsee#1371]
From my experiment and reading the code:

https://github.com/paritytech/jsonrpsee/blob/a4533966b997e83632509ad97eea010fc7c3efc0/client/transport/src/ws/mod.rs#L327

it seems that the username and passwords are simply ignored.

As a workaround, I am able to manually set `Authorization` header with `set_headers` and that works.

Thought it seems that wasm client does not support `set_headers`. Instead it seems to pass the url unmodified, so I suspect (haven't tested yet), the browser will handle `user:pass@` just fine, making it all rather inconsistent.

**Comment by niklasad1** [comment]
> it seems that the username and passwords are simply ignored.

Correct, sure we can add that to be consistent with wasm client
