### ISSUE TITLE
Inheriting HTTP Header Option to RPC middlewares

### ISSUE THREAD

**Issue by shunsukew** [paritytech/jsonrpsee#1388]
With the recent merge of [PR #1305](https://github.com/paritytech/jsonrpsee/issues/1305), different layers of rpc middleware can now share data using Extensions.

Leveraging this functionality, we plan to set HTTP header data within the Request extensions of an RPC middleware call, enabling subsequent middleware layers to process the header information effectively.

In our use case, we aim to log each RPC method call, associating specific HTTP header values with each entry. This includes logging individual lines for each call and multiple lines for batch calls. Additionally, this approach facilitates other scenarios, such as HTTP header validation on a per-RPC method basis.

This can be achieved by passing header information to this [function](https://github.com/paritytech/jsonrpsee/blob/a3307b8c877ae3cf285842cfea10e6bbff2d1d2a/server/src/server.rs#L1285) and setting them to Extensions only when the option is enabled.

---

Using HTTP middleware is one possible approach. However, for websocket requests, the RPC middleware needs to propagate HTTP header as its context data to achieve similar functionality.

**Comment by niklasad1** [comment]
You are basically suggesting to pass the `extensions` from `HTTP request` down to the rpc call such that you access such thing in the rpc middleware?

Sure, let's do that

**Comment by shunsukew** [comment]
Thank you so much, yes exactly!
