### ISSUE TITLE
bug(transport): it should not try to resolve sockaddrs when using `build_with_stream`

### ISSUE THREAD

**Issue by oleonardolima** [paritytech/jsonrpsee#1411]
I've been using and testing the `build_with_stream` method added in https://github.com/paritytech/jsonrpsee/pull/1168, but as `Target` been used in both [`build_with_stream`](https://github.com/paritytech/jsonrpsee/blob/47f6b173452785d6f926284207b2d32df461b30b/client/transport/src/ws/mod.rs#L311-L322) and [`try_connect`](https://github.com/paritytech/jsonrpsee/blob/47f6b173452785d6f926284207b2d32df461b30b/client/transport/src/ws/mod.rs#L429-L485) it's resolving the sockaddrs when creating `Target` from the given `Url`, and leading to two problems:
- it's possibly leaking data as it resolves through a standard connection and not through the preferred data stream passed as a parameter.
- in connections, to `.onion` for example, it leads to an error because it tries to resolve it to sockaddrs which is expected to not be possible, and it's one of the reasons to use the specified data stream, in this case for example `arti_client::DataStream`.

I do see two possible fixes for the problem:
- remove the `sockaddrs` resolution from the `Target` data structure, and do it only on `try_connect_over_tcp`, which is the only place it's being used.
- receive the `Target` as a parameter, with the `sockaddrs` field being an `Option<>` leading to the user to possibly do the resolution when needed. It would also require upstreaming the parameter to ws-client methods as well.

**Comment by niklasad1** [comment]
> remove the sockaddrs resolution from the Target data structure, and do it only on try_connect_over_tcp, which is the only place it's being used.

That's preferred option if possible and I don't want to expose elsewhere if possible.

**Comment by oleonardolima** [comment]
> > remove the sockaddrs resolution from the Target data structure, and do it only on try_connect_over_tcp, which is the only place it's being used.
> 
> That's the preferred option if possible and I don't want to expose elsewhere if possible.

Sure, I worked on that approach on #1412, please let me know what you think.
