### ISSUE TITLE
Websocket: How to map a new connection request followed by json rpc request

### ISSUE THREAD

**Issue by niks3089** [paritytech/jsonrpsee#1420]
I'm establishing a new websocket connection via `wscat` where I am passing custom header. I want to have a way to associate this header or even the connection for the following json rpc requests. When the request method is called, I would like to know the connection context and extract either connection id or session id to fetch the relevant information. How would I do this?

**Comment by niklasad1** [comment]
Hey, if you just want the connection id/session id for the connection in your rpc method implementation you use the [extensions api](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/server_with_connection_details.rs#L39-#L97) to get the connection ID

**Comment by niks3089** [comment]
> Hey, if you just want the connection id/session id for the connection in your rpc method implementation you use the [extensions api](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/server_with_connection_details.rs#L39-#L97) to get the connection ID

I see, will the connection ID be present in the header for a new connection request? I just see this when I make the request

```
"sec-websocket-version": "13", "sec-websocket-key": "tkD7V449nwsf9RIPSdF/vw==", "connection": "Upgrade", "upgrade": "websocket", "sec-websocket-extensions": "permessage-deflate; client_max_window_bits", "host": "localhost:4040"}
```
I would like to be able to map the new connection request to connection where I run the json rpc methods on

**Comment by niklasad1** [comment]
Ok,

You can't access HTTP headers etc using the default server builder instead [have a look at this example using jsonrpsee as service](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/jsonrpsee_as_service.rs) where you can instantiate your rpc service and inject whatever data you want from the HTTP request.

**Comment by niks3089** [comment]
I went over the example and in the rpc method, 
```
#[rpc(server, client)]
pub trait Rpc {
	#[method(name = "trusted_call")]
	async fn trusted_call(&self) -> Result<String, ErrorObjectOwned>;
}

#[async_trait]
impl RpcServer for () {
	async fn trusted_call(&self) -> Result<String, ErrorObjectOwned> {
		Ok("mysecret".to_string())
	}
}
```

How can it access the perConnection object or metrics inside it?

**Comment by niklasad1** [comment]
There are two options:

1. Insert the things you want as extensions in the http request itself without rpc middleware.
2. Use the RpcMiddleware and inject the data you want as extensions in the [Request](https://docs.rs/jsonrpsee-types/0.23.2/jsonrpsee_types/request/struct.Request.html#method.extensions_mut)

**Comment by niks3089** [comment]
> There are two options:
> 
> 1. Insert the things you want as extensions in the http request itself without rpc middleware.
> 2. Use the RpcMiddleware and inject the data you want as extensions in the [Request](https://docs.rs/jsonrpsee-types/0.23.2/jsonrpsee_types/request/struct.Request.html#method.extensions_mut)

Thanks, I tried the second option and instead of injecting the data in the request, I am passing the state into the methods directly. This works.
