### ISSUE TITLE
Deadlock when request is issued when some subscription is active

### ISSUE THREAD

**Issue by svyatonik** [paritytech/jsonrpsee#143]
Steps to repeat:
1) open a connection to the ws-server (e.g. substrate node);
2) subscribe to some notifications stream (e.g. to justifications using `grandpa_justifications`);
3) wait enough time for 5 notifications to be sent by the server (e.g. 20 blocks). DO NOT read any notifications from `jsonrpsee::Subscription`;
4) make request to the server (e.g. `chain_getHeader`) using the same client => deadlock.

The reason is that [notifications channel](https://github.com/paritytech/jsonrpsee/blob/040c4b286ea273e0e0f05ac1363d5e9665e88dd3/src/client.rs#L369) is created with buffer size = 4. When we're trying to send 5th notification using blocking `SinkExt::send().await` [here](https://github.com/paritytech/jsonrpsee/blob/040c4b286ea273e0e0f05ac1363d5e9665e88dd3/src/client.rs#L388), the background thread will stop processing `FrontToBack` requests. So if we have single-threaded client, it'll block [here](https://github.com/paritytech/jsonrpsee/blob/040c4b286ea273e0e0f05ac1363d5e9665e88dd3/src/client.rs#L170), waiting for background thread to issue request and read response. At the same time, background thread is waiting for us to read pending notifications from the channel.

**Comment by niklasad1** [comment]
Right, so the simple fix is to use an unbounded channel? 

It seems tricky to pick the "right" buffer size.

**Comment by tomusdrw** [comment]
IMHO have it user-configured and drop excessive notifications (they usually have an ephemeral nature anyway). If the user is interested in not missing any of them, then they can set the size of the channel high enough. We can't (and imho shouldn't) really back-pressure the server, it would presumably be dropping excessive notifications if the client can't keep up either - you can't stop the external stuff that generates these notifications from making progress really :)

**Comment by niklasad1** [comment]
Fixed by #180
