### ISSUE TITLE
Expose current connections count as request extension

### ISSUE THREAD

**Issue by dinhani** [paritytech/jsonrpsee#1438]
I would like to have the number of active connections exposed as a request extension, so it can be available in the middleware layer to be tracked using our custom metrics.

I cannot find any other way to retrieve this information.

https://github.com/paritytech/jsonrpsee/blob/6c293950fc0eb7c3c2b08d9491de6f33b84047c8/server/src/server.rs#L1048

**Comment by mayconamaro** [comment]
+1 🙏

**Comment by niklasad1** [comment]
Hey,

Are you suggesting to expose the current connection count as snapshot when the connection is established? It can be outdated if the connection is long-lived i.e, lots of connections may be established/dropped.

So what we can do is to inject the [ConnectionGuard](https://docs.rs/jsonrpsee-server/0.24.2/jsonrpsee_server/struct.ConnectionGuard.html) as an extension.

This information can fetched if you are using jsonrpsee as service, [example here](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/jsonrpsee_as_service.rs#L175) but I realized that the ConnectionGuard isn't exposed in that API which we can add as well.

**Comment by dinhani** [comment]
@niklasad1 
Exposing the `ConnectionGuard` would be even better for the reasons you listed.

**Comment by niklasad1** [comment]
Sounds good to me, are you down to make PR for that?
