### ISSUE TITLE
How to enable "gzip,deflate" for Jsonrpsee client?

### ISSUE THREAD

**Issue by f-squirrel** [paritytech/jsonrpsee#1444]
Hi all,

I am trying to enable `gzip, deflate` for Jsonrpsee client.
Meanwhile, I tried the following:

```rust
        let middleware_stack = tower::ServiceBuilder::new()
            .layer(
                tower_http::decompression::DecompressionLayer::new()
                    .gzip(true)
                    .deflate(true),
            );
            
             let client = HttpClientBuilder::default()
            .max_concurrent_requests(MAX_CONCURRENT_REQUESTS)
            .set_headers(headers)
            .max_request_size(50 * 1024 * 1024)
            .max_response_size(50 * 1024 * 1024)
            .request_timeout(Duration::from_secs(120))
            .set_middleware(middleware_stack)
            .build(server_url)
            .unwrap();
```

It fails to compile with the following error:

```plain
the trait `tower::Service<http::Request<hyper::Body>>` is not implemented for `Decompression<HttpBackend>`
```

I am not sure what to do about it. Is there a more straightforward way to implement it?

**Comment by niklasad1** [comment]
Hey @f-squirrel 

You are using an old version of jsonrpsee that doesn't work with tower v0.4, can you update jsonrpsee to something later than  >= v0.23 and try again?

I just tested it on jsonrpsee master with tower v0.4 and it compiles. 
Otherwise please report which version of tower and jsonrpsee you get this on

**Comment by f-squirrel** [comment]
@niklasad1 worked like a charm!
Thank you very much for the prompt reply!
