### ISSUE TITLE
Misleading message in jsonrpsee_server::transport::http::response::method_not_allowed

### ISSUE THREAD

**Issue by dcfreire** [paritytech/jsonrpsee#1451]
Currently jsonrpsee returns "Used HTTP Method is not allowed. POST or OPTIONS is required\n" as the body of the response to any request that is not POST. Either it should actually accept OPTIONS requests, or return "Used HTTP Method is not allowed. POST is required\n".

I understand that a CORS layer can be added to handle OPTIONS requests, but it is not required to reach this message.

**Comment by niklasad1** [comment]
Closed by #1452
