### ISSUE TITLE
`ConnectionState` dropped before HTTP request is finished

### ISSUE THREAD

**Issue by dinhani** [paritytech/jsonrpsee#1467]
I noticed the [`ConnectionState`](https://github.com/paritytech/jsonrpsee/blob/1bfea409145dfa11a76fd1e7b3586ab11fdafe26/server/src/server.rs#L259) struct is being dropped before the request is finished when executing HTTP requests.

I have a custom middleware that uses the `ConnectionGuard` exposed via request extensions, and the number of active requests returned was 0 when it was supposed to be 1.

After some investigation, I found the [`conn`](https://github.com/paritytech/jsonrpsee/blob/1bfea409145dfa11a76fd1e7b3586ab11fdafe26/server/src/server.rs#L1044) instance is held active only for websocket requests, but for HTTP requests handled in the [`else` ](https://github.com/paritytech/jsonrpsee/blob/1bfea409145dfa11a76fd1e7b3586ab11fdafe26/server/src/server.rs#L1135) branch, it is not used, causing the `ConnectionState` and the semaphore permit to be dropped before the request finished executing.

**Comment by niklasad1** [comment]
Yes, you are correct.

Let's inject it in the box future stuff for the `else if` and `else` branches
