### ISSUE TITLE
Question about plans for rpc_api macro workflow

### ISSUE THREAD

**Issue by jbaublitz** [paritytech/jsonrpsee#158]
Hi all, it looks like the current usage of the `rpc_api!{}` macro has some examples in the documentation. Unfortunately, when I try to modify these examples to take more of a task-based handling approach for requests, it appears that the presence of lifetimes in the data structures such as `TypedResponder` causes some problems. Because `RawServer`'s `&mut self` reference in `next_event` must live for as long as the returned `RawServerEvent`, this causes problems when you try to send a `RawServerEvent` or similarly lifetime-oriented data structure to another thread to be processed. This causes the `&mut self` reference to require a lifetime of `'static`. Do you have suggestions for working around this? Will this be changed in the 0.2.0 release?

**Comment by niklasad1** [comment]
To be honest, we haven't come that far with the `v2` so `macro design` is still an open question.
