### ISSUE TITLE
WASM friendly dependencies

### ISSUE THREAD

**Issue by olanod** [paritytech/jsonrpsee#175]
Not only to make maintenance easier but also to potentially enable WASM compilation what about using higher level HTTP and WebSocket abstractions like [`surf`](https://github.com/http-rs/surf)(I guess better for async-std environments?) or `reqwest` and for WS perhaps something like [`ws_stream_wasm`](https://github.com/najamelan/ws_stream_wasm) at least for the client stuff?

**Comment by niklasad1** [comment]
Ok cool,

I think it's worth investigating for the client as you suggested, [`surf`](https://github.com/http-rs/surf) looks nice and [`ws_stream_wasm`](https://github.com/najamelan/ws_stream_wasm) would require some conditional compilation because it only works for `WASM`.

**Comment by olanod** [comment]
For non WASM seems like [ws_stream_tungstenite](https://github.com/najamelan/ws_stream_tungstenite) is the native equivalent

**Comment by niklasad1** [comment]
> For non WASM seems like ws_stream_tungstenite is the native equivalent

After https://github.com/paritytech/jsonrpsee/pull/171 we assume that separate sender and receiver of the WebSocket stream exist which [tungstenite-rs](https://github.com/snapview/tungstenite-rs) doesn't provide and it doesn't has support for async/await AFAIU).

Thus, it's a not an ideal library for us but the [`ws_stream_wasm/JS bindings`](https://github.com/najamelan/ws_stream_wasm) implements at least `Sink` and `Stream` which is good.

**Comment by olanod** [comment]
The one I linked is from the same person behind `ws_stream_wasm` is not `tungstenite-rs` but something on top that implements the same interface.

**Comment by niklasad1** [comment]
https://github.com/paritytech/jsonrpsee/pull/204 is merged which replaced hyper with  [`surf`](https://github.com/http-rs/surf). Thus, it now builds for WASM but I haven't tested it yet.

You have to disable the `default-features` and enable `--feature wasm-client` similar to [what the CI does](https://github.com/paritytech/jsonrpsee/blob/master/.github/workflows/ci.yml#L84)

**Comment by niklasad1** [comment]
Sorry, we had to revert #204 because `surf` brought in `OpenSSL` as a dependency which I didn't realize and it is [not possible to disable](https://github.com/http-rs/surf/issues/219) but when/if it becomes possible to enable TLS on it (ideally with `rustls`), then we could move back to use `surf` again.

I left the [branch open](https://github.com/paritytech/jsonrpsee/tree/http-client-surf) if you want to use still.

**Comment by olanod** [comment]
I think https://github.com/http-rs/surf/pull/271 would be the PR to track for that

**Comment by athei** [comment]
> I think [http-rs/surf#271](https://github.com/http-rs/surf/pull/271) would be the PR to track for that

I think that PR is merged and should be released by now?

**Comment by niklasad1** [comment]
Right, yeah thanks for letting us know but we still need `tokio 1.0` support for this to work :(

Closing this issue in favor of https://github.com/paritytech/jsonrpsee/issues/227
