### ISSUE TITLE
Implement proper access control in jsonrpsee-http

### ISSUE THREAD

**Issue by tomaka** [paritytech/jsonrpsee#2]

**Comment by tomaka** [comment]
Basically we should reproduce the capabilities here: https://github.com/paritytech/jsonrpc/blob/97b08dae468142352aad31b8f6df237c7c192e62/http/src/lib.rs#L193-L567

**Comment by dpmkl** [comment]
Hi, 
I would not mind giving that a go, some initial questions: 

- Can we reuse code used in jsonrpc such as the Hosts struct and DomainValidation for this ? 
- Given the commented out code for CORS in process_request, I assume the access control should be analogous ? 
- Is there a need for socket level access control or only based on the http header "host" in the hyper request ? 
- The link refers to a builder pattern which is not present in the current code base, is this pattern abandoned or just not implemented yet? 

Happy for pointers in the right direction :)

**Comment by tomaka** [comment]
Hi!

Before you submit a PR, I need to quickly ask around what exactly the license of this repo would be (most likely the same as paritytech/jsonrpc), and see if the CLA is needed.

> Can we reuse code used in jsonrpc such as the Hosts struct and DomainValidation for this ?

Yes!

> Given the commented out code for CORS in process_request, I assume the access control should be analogous ?

> Is there a need for socket level access control or only based on the http header "host" in the hyper request ?

I personally don't really know what the use-case of CORS is, and my idea is just to reproduce the capabilities of the jsonrpc crate.

> The link refers to a builder pattern which is not present in the current code base, is this pattern abandoned or just not implemented yet?

Just not implemented yet. I think we should have a builder as well.

**Comment by tomaka** [comment]
> what exactly the license of this repo would be (most likely the same as paritytech/jsonrpc)

Oh nevermind, I had already put the MIT license.

**Comment by tomaka** [comment]
And there's now a CLA bot!

**Comment by dpmkl** [comment]
K, I'll get that sorted out.
I started work on branch what will hopefully be a PR by the weekend.

**Comment by niklasad1** [comment]
Closed by #31
