### ISSUE TITLE
Homogenize WS and HTTP servers and clients

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/jsonrpsee#219]
Follow up to #174, the new ws-server introduced a set of types to speed up serialization and deserialization of the JSON, it would be nice if those can be re-used, and having the API somewhat similar.

- [x] Make http and ws servers use the same `JsonRpcX` structs.
- [x] Make the servers and clients use the same `JsonRpcX` structs.
- [x] Make the API between http and ws servers same-ish.

**Comment by niklasad1** [comment]
Closed by #269
