### ISSUE TITLE
Networking error when handling separate https conn over ws client

### ISSUE THREAD

**Issue by gregdhill** [paritytech/jsonrpsee#230]
Seems processing a separate http connection ([for example](https://github.com/interlay/polkabtc-clients/blob/dev/vault/src/faucet.rs#L41)) over an existing `WsClient` forces the background task to close. Logs here: https://gist.github.com/gregdhill/01bf4e081e2f8faf3dfac19165a96b9b

**Comment by niklasad1** [comment]
Hey, I don't understand exactly what you are trying to do.

But for the logs I can see that first `HTTP client` is dropped and then `WebSocket client` is dropped:

```
[2021-03-09T07:31:11Z TRACE hyper::proto::h1::dispatch] client tx closed 
[2021-03-09T07:31:11Z TRACE jsonrpsee_ws_client::client] [backend]: frontend channel dropped; terminate client
```

Thus, doesn't look like a `jsonrpsee` issue to me.

**Comment by gregdhill** [comment]
If I skip `jsonrpc_http::connect` on the client the websocket client works fine, which leads me to believe it could be a `jsonrpsee` issue.

**Comment by gregdhill** [comment]
Issue wasn't related to jsonrpsee, closing...
