### ISSUE TITLE
[ws client]: don't cancel background thread in case a request has been dropped

### ISSUE THREAD

**Issue by gregdhill** [paritytech/jsonrpsee#233]
It would seem that failing to send a response on request terminates the client: https://github.com/paritytech/jsonrpsee/blob/cf2a5a7750baee0e1bc7693ec24e482fc162327d/ws-client/src/client.rs#L381

Can this be handled? Probably we don't want to terminate the client if a single connection is dropped.

Let me know if I missed anything!

**Comment by niklasad1** [comment]
It's by-design I wrote about https://github.com/paritytech/jsonrpsee/issues/67#issuecomment-763126990 to be on the safe side for now, it's tricky to understand each scenario where it's safe to resume but probably just connection errors are not recoverable.

Thus, you need restart the client once an error occurs for now. However, we should fix https://github.com/paritytech/jsonrpsee/issues/188

It could be improved as follows:
- If it's possible to deserialize the response then we could figure it which request failed and propogate it accordingly to the frontend
- ConnectionError terminate the background thread
- Other just ignore

**Comment by gregdhill** [comment]
As I understood it, `send_back_oneshot` would only return `Some(Err(Ok(_)))` if the receiver on the front-end is dropped. In this case the fault wasn't on the remote server but on the library consumer.

**Comment by niklasad1** [comment]
ahh, I see what you mean.

yeah, I agree that should just be ignored.
