### ISSUE TITLE
[jsonrpsee root crate]: more configurations for internal crates through feature flags.

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#271]
- Make it possible to just include a specific server or client, currently we include on all transport behind the features `server` and `client`, see https://github.com/paritytech/jsonrpsee/pull/260#discussion_r607844283_ for further information

**Comment by dvdplm** [comment]
I have doubts about whether we should continue supporting tokio 0.2.

**Comment by niklasad1** [comment]
I agree that we should deprecate `tokio 0.2` in the next release, so maybe we could continue support `tokio 0.2` in jsonrpsee v0.3 or something
