### ISSUE TITLE
[jsonrpsee types]: provide macro for constructing JsonRpcParams

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#275]
The `JsonRpcParams` are a little boiler-platy to provide as we require the arguments to be `serde_json::Value`, 

Example:
```rust
// MyType doesn't implement `Into<serde_json::Value>`
let x: = MyType { };
let inner: &[JsonValue] = &[0_u32.into(), "hoo".to_string().into(), serde_json::to_value(x).unwrap()];
let params =  JsonRpcParams::ArrayRef(inner);
```

So it would be nice is to provide a macro such as `params_positional!` and `params_object` to avoid that.
Perhaps just provide a wrapper on-top of [serde_json::json!](https://docs.serde.rs/serde_json/macro.json.html)?

Note: Copy @kianenigma's stuff.

**Comment by dvdplm** [comment]
Maybe it's possible to unify the client `JsonRpcParams` with the servers'?

**Comment by niklasad1** [comment]
> Maybe it's possible to unify the client JsonRpcParams with the servers'?

The problem is that the server-side `RpcParams` is a wrapper over Cow<&str> and is used to deserialize the types within a request and `JsonRpcParams` is only used to serialize the types. 

In order to unify them we would have to explicitly require to that user provide a `&str/String` for the params such as `"[1, 2, "foo"]"` which is very annoying in my experience. It could be possible to have that but we would still need some convenience method(s) to convert a Vec<T: serde::Serialize> to `&str/String` if that's possible to with a macro that would be awesome ^
