### ISSUE TITLE
Properly implement and test server-side subscriptions

### ISSUE THREAD

**Issue by tomaka** [paritytech/jsonrpsee#3]
There are drafts everywhere, but it's not properly implemented.

**Comment by tomaka** [comment]
The design idea is that when a server generates a request, you can turn it into a "subscription" by calling `ServerRequest::into_subscription`. When doing so, you can pass some user data to said subscription, that the `Server` struct will store.

The natural way of using this API is to hold for example a list of all the `SubscriptionId` that must be broadcasted a new block. Then, whenever a new block is generated, we look at all the elements of that list and send out the block. Looking at all the elements of the list is done synchronously wherever any block is generated.

This is for example how you'd do it:

```rust
pub struct RpcServer {
    server: jsonrpsee::HttpServer,
    on_block_generated: HashSet<jsonrpsee::ServerSubscriptionId>,
}

impl RpcServer {
    pub async fn next_step(&mut self) -> Result<(), ()> {
        match MyApi::next_request(&mut self.server).await? {
            // ... somehow answer requests here ...
            // ... or push to on_block_generated if it's a subscription ...
        }
    }

    pub async fn report_block_generated(&mut self, event: ...) {
        for id on self.on_block_generated.iter() {
            self.server.subscription_by_id(id).unwrap().send(event).await;
        }
    }
}
```

This would be a straight-forward state machine.

The unsolved questions are:

- How do we detect when the user closes the connection (and thus that we must kill the subscription)? Right now there's a draft for a `is_valid` method on `ServerSubscription` that you're supposed to call regularly to see if the connection is still alive. Should we modify the `RawServer` trait to add an event when that happens?
- How do we make that into a nice API for the `rpc_api!` macro?

**Comment by tomaka** [comment]
Another challenge is that subscriptions aren't necessarily immediately active when the user decides.

If there is a batch of, say, three subscription requests and two regular requests, we need to answer all five items before starting to send out subscription events.

Due to the design of the library, the user answers requests one by one and the pending responses are buffered. But this means that the user must not process a subscription request then immediately start sending out events.

**Comment by tomaka** [comment]
Above points have been resolved.
The last remaining design issue with the `Server` is this TODO: https://github.com/paritytech/jsonrpsee/blob/51fa678252a6924e2172e461c0fad71331bdedcb/core/src/server/core.rs#L347

Calling `respond` should in my opinion immediately send back the response, rather than sending it the next time we call `next_event`. This is way harder than it looks, though, because the `BatchesState` struct hasn't been designed for that.

**Comment by niklasad1** [comment]
Closing as we have some integration tests for testing subscriptions and unsubscribing.
