### ISSUE TITLE
[ws client] How to handle incoming notifications?

### ISSUE THREAD

**Issue by billylindeman** [paritytech/jsonrpsee#301]
I'm using jsonrpsee to implement a websocket rpc client, and I need to handle some incoming notifications.  I don't see a way to register a handler for incoming notifications and curious if I'm missing something in the docs / examples.  Is this not supported?

Thanks!

**Comment by niklasad1** [comment]
> I'm using jsonrpsee to implement a websocket rpc client, and I need to handle some incoming notifications. I don't see a way to register a handler for incoming notifications and curious if I'm missing something in the docs / examples. Is this not supported?

I assume you are using the `jsonrpsee ws server` to integrate with your client implementation? 
Currently, we have no `separate` notification handling for this manually because it's more or less useless because

> The Server MUST NOT reply to a Notification, including those that are within a batch request.

but we should add it to comply with spec for sure

However, for simple testing I think you could just add as `dummy method`:

```
server.register_method("say_hello", |_| Ok("")).unwrap();
```

**Comment by billylindeman** [comment]
@niklasad1  I'm not using a jsonrpsee ws server, I'm writing a client that connects to a websocket jsonrpc2 server written in go.  The server can send async notifications to the client that I need to listen for and handle appropriately.  Any thoughts on how this could be implemented?

**Comment by niklasad1** [comment]
Ok,

We, do handle async notifications (we call them subscriptions) in the client from the server by having a background thread that listens for messages then the if message could be decoded as a subscriptions it's propagated to the user. 

[Docs here](https://docs.rs/jsonrpsee-types/0.2.0-alpha.6/jsonrpsee_types/traits/trait.SubscriptionClient.html#tymethod.subscribe)

**Comment by billylindeman** [comment]
`let mut subscribe_hello: Subscription<String> =
		client.subscribe("subscribe_hello", JsonRpcParams::NoParams, "unsubscribe_hello").await?;`

@niklasad1 Is it possible to register a notification handler using this mechanism...? It seems this has extra stuff built on top of the jsonrpc2 notification concept.  How can I just create a subscription for a given method or methods, without subscribe/unsubscribe.. or having a subscription_id in the payload (again the server I'm connecting to is not rust/jsonrpsee it's standard jsonrpc2-ws). 

If it's not possible I think this ticket should remain open as a client version of #302

**Comment by billylindeman** [comment]
Yep exactly, It seems if I could create a "manual" Subscription<T> that is attached to an incoming method name this would support the notification spec and would be a slick interface for it :) 

For more context: I'm using jsonrpsee to create a rust webrtc client that connects to a websocket signaling server.  In our go client we are able to register a Handle() callback that will get triggered for incoming notifications https://github.com/cryptagon/ion-cluster/blob/master/pkg/client/signal.go#L119.

**Comment by dvdplm** [comment]
@billylindeman I agree this seems like something we may want to support. Do you have a suggested API that you would like to see supported? If it's not too much trouble, it would help us if you could type out an example interaction you'd like to see working.
