### ISSUE TITLE
[servers]: add register_notification API

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#302]
We don't have an API for register JSON-RPC notifications (a call without a request ID)

However, for `HTTP` if a request could be de-serialized as as notification we simple `ACK` it by sending an empty response on it such that the client won't wait for it forever and for `WS` we simply ignore.

Thus, I don't think we need to have a separate API for because `register_method` seems useless as those are simply ignored.

Maybe I'm missing something?

**Comment by dvdplm** [comment]
Closed by #303

**Comment by niklasad1** [comment]
No, #303 fixed it on the client-side we still doesn't support pure notifications in the servers.

**Comment by jsdw** [comment]
We don't have a use case for this, so while we would happily accept contributions of this sort, we'll close the issue for now since it's been inactive for a while. Feel free to re-open if you'd like to contribute.
