### ISSUE TITLE
[rpc module]: possibility to re-use modules on different servers.

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#328]
The `RpcModule` doesn't implement `Clone` and ideally we should some way to construct it once and re-use it to register on several servers such as running the servers on different ports or something similar.

```rust
let module = RpcModule::new();
ws_server.register_module(module.clone());
http_server.register_module(module.clone());
```

Best way is probably to provide some builder that merges the modules when `server.start` is called.

**Comment by maciejhirsz** [comment]
This should be easily achievable by making the `Methods` use `Arc<HashMap<_, _>>` internally, using `Arc::make_mut` for adding new methods. Sync methods will need to change from `Box<dyn _>` to `Arc<dyn _>` like async methods, which should also unlock a straight forward way to do method aliasing (#378).
