### ISSUE TITLE
The dependency bug

### ISSUE THREAD

**Issue by fewensa** [paritytech/jsonrpsee#352]
https://github.com/paritytech/jsonrpsee/blob/4a29388a6d221d8ddfa45f6881cbffefb914e35d/ws-client/Cargo.toml#L18

There need change to 

```toml
jsonrpsee-types = { path = "../types", version = "=0.2.0-alpha.7" }
```

Documents:

https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements

For example:

Now, the [parity-bridges-common](https://github.com/paritytech/parity-bridges-common) use 0.2.0-alpha.6

https://github.com/paritytech/parity-bridges-common/blob/643f10db48314e2b366f323e176b8b42024a4a2e/relays/client-substrate/Cargo.toml#L12-L13

If I create a new project dependency to parity-bridge-common/relays/client-substrate, According to cargo's rules, will have such a dependency 

```text
decode-test v0.1.0 (/dev/decode-test)
└── relay-substrate-client v0.1.0 (https://github.com/paritytech/parity-bridges-common?rev=66e1508127ff5104d3d18f9bbf9ea9997055d1d5#66e15081)
    ├── jsonrpsee-ws-client v0.2.0-alpha.6
    │   ├── jsonrpsee-types v0.2.0-alpha.7
```

Next, such an error will occur 

```text
error[E0432]: unresolved import `jsonrpsee_types::v2::parse_request_id`
 --> d:/opt/scoop/persist/rustup/.cargo\registry\src\github.com-1ecc6299db9ec823\jsonrpsee-ws-client-0.2.0-alpha.6\src\helpers.rs:5:5
  |
5 | use jsonrpsee_types::v2::parse_request_id;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `parse_request_id` in `v2`

error[E0432]: unresolved import `jsonrpsee_types::v2::error::JsonRpcErrorAlloc`
 --> d:/opt/scoop/persist/rustup/.cargo\registry\src\github.com-1ecc6299db9ec823\jsonrpsee-ws-client-0.2.0-alpha.6\src\helpers.rs:8:23
  |
8 | use jsonrpsee_types::{v2::error::JsonRpcErrorAlloc, Error, RequestMessage};
  |                       ^^^^^^^^^^^-----------------
  |                       |          |
  |                       |          help: a similar name exists in the module: `JsonRpcError`
  |                       no `JsonRpcErrorAlloc` in `v2::error`
```

**Comment by niklasad1** [comment]
yeah, you are correct meanwhile just do `cargo update -p jsonrpsee-types --precise 0.2.0-alpha.6`

**Comment by niklasad1** [comment]
Closed by #353 but it will take a while until a new version if published.

**Comment by fewensa** [comment]
The new release tag have same question.

https://github.com/paritytech/jsonrpsee/blob/3f804de16c4ce07cd40b8677cb610d418afaa8b6/ws-client/Cargo.toml#L26

**Comment by niklasad1** [comment]
No, because `0.2.0` is released then we will have to respect semver and fetching a later version such as `0.2.1` should still work as it's backward compatible with all `0.2.x` versions.

Users can manually select which version of `jsonrpsee` via their `Cargo.lock` file
