### ISSUE TITLE
[ws server]: add builder 

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#361]
The `WebSocket server` should have a similar builder pattern [as the HTTP server](https://docs.rs/jsonrpsee-http-server/0.2.0-alpha.7/jsonrpsee_http_server/struct.HttpServerBuilder.html)

Then provide functionality to configure it properly such as `CORS`, `max body size` and so on.

**Comment by dvdplm** [comment]
There is some duplicated code in the ws/http servers atm. I will not address that as part of this ticket, but something to ponder.

**Comment by niklasad1** [comment]
Closed by #365
