### ISSUE TITLE
[tracking] substrate integration

### ISSUE THREAD

**Issue by dvdplm** [paritytech/jsonrpsee#379]
Tracking ticket for substrate integration, add items as needed.

- [x] Testing: expose the `execute` method on `Method` and add an "unsafe" method to construct the JSON string to pass to it to allow tests to not spin up a whole server. We need a testing sink as well to read the result off of.
- [x] Build a free-standing high level test suite for the RPC methods in substrate (and likely polkadot down the line) to validate the full JSON responses of method calls and subscriptions in substrate. Use the existing testing machinery from `sidecar` as inspiration (or extract it from sidecar and use it in both?)

**Comment by niklasad1** [comment]
I think this is fixed, closing
