### ISSUE TITLE
Proc macro tweaks

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/jsonrpsee#403]
+ [x] Remove old macro code, update examples to new macro code.
+ [x] Remove allocations in param parsing by using `RpcParams::next` and `RpcParams::optional_next` (#401) in the generated code.

CC @popzxc

**Comment by popzxc** [comment]
>  Remove allocations in param parsing by using `RpcParams::next` and `RpcParams::optional_next` ([Streaming RpcParams parsing #401](https://github.com/paritytech/jsonrpsee/pull/401)) in the generated code.

If I understood the linked PR correctly, it only works for the array params. What about object params? Should we fall back to the allocation-based deserialization in that case?

**Comment by popzxc** [comment]
I'd add the following to the list:

```markdown
- [ ] Add more UI tests.
- [ ] Add tests for missing parameter deserialization (if the parameter is an `Option`, it should still work).
- [ ] Improve auto-generated doc-comments:
  - Subscriptions descriptions should include the type of yielded items.
  - Provide a way for users to extend auto-generated doc-comments (there must be a way to add descriptions to both server- and client-side parts).
- [ ] Rewrite `no_run` examples in doc-comments to the actual doc-tests (otherwise they'll become outdated at some point).
- [ ] Add a way to set up an associated type for the RPC-specific `Error` type.
```

**Comment by dvdplm** [comment]
>     Add a way to set up an associated type for the RPC-specific Error type.

@popzxc Can you elaborate a bit on this, not sure I follow?

**Comment by popzxc** [comment]
> Can you elaborate a bit on this, not sure I follow?

Currently, in the RPC server implementation, you may return the `Result<OkVal, CustomErr>` from your method, but it still will be deserialized as `<CallError>::Ok(<CustomErr>::Err(YourErrorType { ... }))`.

While it will work and (kinda) serve its purpose, it's still a clunky way to deal with errors, and it's not how RPC is supposed to work.

I want the macro to be able to handle something like:

```rust
#[rpc_error] // <- Implies `serde::{Serialize, Deserialize}`, `Into<CallError>` and `derive(thiserror::Error)`.
enum CustomError {
    #[error("Bad number: {0}")] // <- error message is derived from the `thiserror::Error` implementation
    BadNumber(u32) = 42, // <- error code.
                        // ^- thanks to `serde`, this object will go into the `data` field.
}

#[rpc(client, server)
trait Rpc {
    type Error = CustomError; // <- Now we can return our own errors.
    #[method(name = "foo")
    fn foo(&self, input: u32) -> Result<bool, CustomError>; // We now will be able to flatten `CustomError` and `CallError`.
}
```


with this approach, there will be no `Ok(Err(...)`, but rather a simple

```rust
// Pseudocode
Err(
    CallError::Custom {
        code: 42,
        message: "Bad number: 42",
        data: Some(RawValue("CustomError: { BadNumber: 42 }")) // Don't quite remember how serde encodes enums by default.
    }
)
```

**Comment by popzxc** [comment]
However, the content of the comments is not yet the fully-fledged design I want to propose.

We must think about it thoroughly to not provide an obscure mechanic that relies on too much under-the-hood magic, it must be fluent and simple enough to understand from a quick glance (and maybe a couple of sentences in docs), and it should make sense.

**Comment by popzxc** [comment]
Yup, exactly.

---

I'm sorry I've disappeared from the project without finishing what I started. Got overwhelmed with the main job after vacation 😓

**Comment by niklasad1** [comment]
Ok, got it thanks.

Ah no worries, still super grateful for your work :pray:

**Comment by niklasad1** [comment]
Closing this in favor of #417
