### ISSUE TITLE
Access CallError without macros

### ISSUE THREAD

**Issue by That3Percent** [paritytech/jsonrpsee#407]
If you need to access `CallError` (which is used in the signature of `register_async_method`) the only path to do so is through `types::error::CallError`. But, the `types` crate is only available if the `macros` feature is included.

This is undesirable. Instead, `CallError` should be re-exported from the `http_server` crate, or the `types` crate should be available when the `server` feature is specified.

**Comment by dvdplm** [comment]
I agree and have had the exact same thought.
