### ISSUE TITLE
Cannot parse `RpcParams` on another thread

### ISSUE THREAD

**Issue by That3Percent** [paritytech/jsonrpsee#408]
JSON parsing is a surprisingly expensive operation. It is desirable to be able to parse JSON in the thread which handles the request, rather than the "main" thread producing requests. Otherwise, throughput is limited.

I would like to be able to write:
```rust
module.register_async_method("challenge", move |rpc_params, context| {
    return (async move {
        let outcome = tokio::spawn(async move {
            let challenge = rpc_params.parse()?;
```

But instead need to write:
```rust
module.register_async_method("challenge", move |rpc_params, context| {
    let challenge = rpc_params.parse();
    return (async move {
        let outcome = tokio::spawn(async move {
            let challenge = challenge?;
```
because of the lifetime in `RpcParams`.

One could `.to_owned()` to get an `OwnedRpcParams` but this is an unnecessary performance drain in it's own right.

The `register_async_method` implementation already has access to an `OwnedRpcParams` which it does not make use of. It would be preferable to transfer ownership to the callback to avoid the unnecessary performance overhead.

**Comment by maciejhirsz** [comment]
`register_async_method` is converting `RpcParams` to `OwnedRpcParams` internally, so calling `.to_owned()` is the way to do it if you want to spawn execution on a separate task. It does cost you one allocation, but that should be acceptable cost once you account for all the IO and moving stuff to a separate task.

**Comment by That3Percent** [comment]
Why not pass the existing `OwnedRpcParams` in (jsonrpsee 0.3.x)?

**Comment by maciejhirsz** [comment]
There isn't one:

https://github.com/paritytech/jsonrpsee/blob/ddb508063269d510210caa106da68b8fad20eeae/utils/src/server/rpc_module.rs#L53-L57

`RpcParams` borrows JSON slice from `JsonRpcRequest`, which in turn borrows it from input buffer that's shared between requests, so the lifetime restriction is necessary. To avoid doing that we'd have to create a separate owned buffer for each request, but that's just pushing that one extra allocation into a different place, and forcing you to pay for it every time, even when you might not need it.

**Comment by That3Percent** [comment]
There is an owned one, it's just created a few lines further down...

[https://github.com/paritytech/jsonrpsee/blob/ddb508063269d510210caa106da68b8fad20eeae/utils/src/server/rpc_module.rs#L63](https://github.com/paritytech/jsonrpsee/blob/ddb508063269d510210caa106da68b8fad20eeae/utils/src/server/rpc_module.rs#L63)

I think it round trips back to the borrowed version here:
[https://github.com/paritytech/jsonrpsee/blob/095db9b2d5d25f4ba822ff5878150563f1643f41/utils/src/server/rpc_module.rs#L229](https://github.com/paritytech/jsonrpsee/blob/095db9b2d5d25f4ba822ff5878150563f1643f41/utils/src/server/rpc_module.rs#L229)

I'd be fine with either fix (either share the buffer, or transfer the owned object).

**Comment by maciejhirsz** [comment]
> There is an owned one, it's just created a few lines further down...

...for registered async callbacks _only_, that's why async gets `OwnedRpcParams` while sync gets `RpcParams` with a lifetime: sync does not pay any extra allocation costs by default.

You can do `OwnedRpcParams::from(params)` in your code and it will have the same exact cost as getting one in async callback.

**Comment by That3Percent** [comment]
Yes, I realize this is for registered async callbacks. As I stated in the original post up top that I would like `register_async_method` to take `OwnedRpcParams` rather than doing an unnecessary round trip like it does now.

**Comment by maciejhirsz** [comment]
Ah right, I thought you wanted to spawn the task in sync callback, my bad. Yeah, we can definitely do that.

**Comment by That3Percent** [comment]
Thanks!
