### ISSUE TITLE
Client seems to ignore the query parameters of a WSS address

### ISSUE THREAD

**Issue by kukabi** [paritytech/jsonrpsee#428]
I'm trying to connect to an OnFinality RPC service and failing with `401 - Unauthorized`. The endpoint is in the format `wss://kusama.api.onfinality.io/ws?apikey={API_KEY}`, and I'm able to connect to the endpoint using a simple websocket client, which makes me think that the `API_KEY` query parameter is being ignored when the client is trying to connect to the service. I can connect to the simple RPC endpoints using the same code (e.g. `wss://kusama-rpc.polkadot.io`).

**Comment by niklasad1** [comment]
Hey,

It looks like you are right, basically we are using [Url::path](https://docs.rs/url/2.2.2/url/struct.Url.html#method.path) to get path and that ignores `query` and `fragment`. 

Thus, we need to fetch those and construct a `new String` that is in this case `/ws?apikey={API_KEY}`

**Comment by kukabi** [comment]
Thanks @niklasad1, #429 is working fine here.
