### ISSUE TITLE
Whether jsonrpsee will support http server middleware like jsonrpc-core

### ISSUE THREAD

**Issue by KaoImin** [paritytech/jsonrpsee#437]

**Comment by dvdplm** [comment]
That is undecided. What is your use-case if I may ask?

**Comment by KaoImin** [comment]
> That is undecided. What is your use-case if I may ask?

I used middleware to do RPC relay. In detail, In detail, the middleware will determine whether it needs to be processed or relayed to a specific host on receiving a request.

**Comment by dvdplm** [comment]
We merged https://github.com/paritytech/jsonrpsee/pull/576 today which adds some support for middleware. I'd say it does not cater to your use case though and I'm not wholly convinced middleware is a good fit for load balancing. I'll close this issue now as it's more of a question.

It'd be great if you could open a feature request issue to argue for your RPC relay use-case and we can discuss further there. :)
