### ISSUE TITLE
[proc macros]: support for named parameters (JSON Map/Object)

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#445]
Currently in proc macros one implementation for named parameter(s) exist [here](https://github.com/paritytech/jsonrpsee/blob/master/proc-macros/src/render_server.rs#L301-#L336)

The reason why it's not used is because it won't work to have a serde implementation inside a trait impl with generic type parameters, thus one would a get compile error such as `can't use generic parameters from outer function`.

The reason for this is how the `RpcServer trait` is generated.

```rust
pub trait RpcServer<T> {
   // defined methods without impls
   async fn foo() -> Result<(), Error>;


  ///Collects all the methods and subscriptions defined in the trait and adds them into a single `RpcModule`.
  fn into_rpc(self) -> jsonrpsee::RpcModule<Self> {
       // registering methods and decoding params goes here (which is problematic for serde impls)
  }
}
```

**Comment by dvdplm** [comment]
This could use a good description and a design suggestion.
