### ISSUE TITLE
[proc macros]: improve `is_option`helper

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#447]
The implementation is a bit naive and should investigated and tested further.

Not sure why anybody would, but it may also be useful to test that `std::option::Option` works, and maybe test that something stupid like `foo::Option::Bar` doesn't work?

_Originally posted by @jsdw in https://github.com/paritytech/jsonrpsee/pull/446#discussion_r700151588_

**Comment by dvdplm** [comment]
Both `std::option::Option` and `core::option::Option` should work. And then there's the pesky issue of re-exports. Some crates re-export parts of `std`/`core`.

**Comment by niklasad1** [comment]
Fixed by #441
