### ISSUE TITLE
Please add session ID

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/jsonrpsee#452]
I have a use case that requires me knowing that messages and subscriptions belong to the same client.

Having an ID on `Session` struct would make it possible. I can make a PR if this is a welcome change.

UPD: And I'd need access to it on requests, not just subscriptions.

**Comment by niklasad1** [comment]
//cc @maciejhirsz 

could be solved by having RPC module middleware too maybe? if we expose the connection ID I suppose...

**Comment by dvdplm** [comment]
Closing as stale.
