### ISSUE TITLE
Rename and reorganise types a bit

### ISSUE THREAD

**Issue by dvdplm** [paritytech/jsonrpsee#457]
Currently (v0.3) we have many types prefixed with `JsonRpc`, e.g. `JsonRpcRequest`, `JsonRpcInvalidRequest`, `JsonRpcResponse`, `JsonRpcSubscriptionParams` etc.

Rename such types without the `JsonRpc` prefix, `Request`, `InvalidRequest`, `Response` etc.

The rationale for adding the `JsonRpc` prefix in the first place was to signal that the type is part of [the spec](). It'd be good to continue having a clear separation between types stemming from the spec and types that are implementation specific. Today, most types in `jsonrpsee-types::v2` are from the spec.

While rummaging with the types it might be a good time to also figure out what to do about: 
- `v2::params::JsonRpcSubscriptionParams`: maybe not actually parameters? I think it's the subscription item response type?
- `v2::request::JsonRpcNotification`: isn't this a response types, and if yes, let's move it to `v2::response` (EDIT: see [the conversation here](https://github.com/paritytech/jsonrpsee/pull/459#discussion_r706199657))
- https://github.com/paritytech/jsonrpsee/blob/e62a0decd7cad25b7aea72e4e783d8322e99f7f6/types/src/v2/request.rs#L149

**Comment by dvdplm** [comment]
>     * // TODO(niklasad1): merge the types `JsonRpcParams` and `RpcParams` and remove `RawValue`.

@niklasad1 Do you think you can elaborate on this todo a bit? After this PR we have `JsonRpcParams` renamed to `Params` and `RpcParams` (an enum) renamed to `ParamsSer`. How do you suggest we merge them? Do you mean replacing 

```
	#[serde(borrow)]
	pub params: Option<&'a RawValue>,
```

…with

```
        #[serde(borrow)]
	pub params: ParamsSer<'a>,
```

That seems tricky!

**Comment by niklasad1** [comment]
Just remove the `TODO`, 

I though that it could possible to introduce a new type that did both serializing and deserializing but it includes extra cost in terms of allocations.

Further, we have build a lot of stuff around `RpcParams(Option<RawValue>)` it doesn't make sense anymore
