### ISSUE TITLE
Include more information in `CallError::InvalidParams`

### ISSUE THREAD

**Issue by dvdplm** [paritytech/jsonrpsee#460]
Change [`CallError::InvalidParams`](https://github.com/paritytech/jsonrpsee/blob/d2e574243295adcfbfe5f29eb0e59f986495ff8a/types/src/error.rs#L48) to include more information to make debugging easier.
This could be as easy as having `InvalidParams(String)` or we include a proper error type from serde.

**Comment by niklasad1** [comment]
Fixed by #463
