### ISSUE TITLE
Method not found diagnostics could suggest likely methods

### ISSUE THREAD

**Issue by gilescope** [paritytech/jsonrpsee#482]
It would be pretty cool if when you hit a "Method not found" it would (maybe only when built in debug) suggest other method(s) that sounded similar to that method.

Touches like this make developing with such libraries a pleasure and reduce head scratching leading to better cycle times.

Example of prior art:
```sh
> cargo chk                                                                                                                      127.DONT PANIC
error: no such subcommand: `chk`

	Did you mean `c`?
```

**Comment by dvdplm** [comment]
I wouldn't be opposed to this (not in release mode though). Something you'd be interested in contributing @gilescope ?

**Comment by gilescope** [comment]
I am a disciple in the ways of esteban. Making things easy to use is
essential. I’ll happily give it a crack.

**Comment by dvdplm** [comment]
@gilescope this is a potential DoS vector so whatever we end up doing here, it should be debug-only.

**Comment by gilescope** [comment]
I think the error messages are strings now not &’static str so it’s a bit
easier now.

we could wire it up to unsafe flag?

**Comment by jsdw** [comment]
We'll happily accept contributions for this (though one would need to consider the performance overhead and such), but we don't really have any plans to work on it, so for now I'll close the issue.
