### ISSUE TITLE
[ws server]: check length of response before sending it via soketto

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#536]
After reading some soketto code I realized that the `max_payload_size` only applies to the `Receiver` and not `Sender`.

Thus, when sending we need to check that the payload doesn't exceeds the `max_limit`

**Comment by dvdplm** [comment]
Can you add this to the 0.5 tracking issue please?

**Comment by niklasad1** [comment]
Closed by https://github.com/paritytech/jsonrpsee/pull/553
