### ISSUE TITLE
Can I call server.start() twice

### ISSUE THREAD

**Issue by KaoImin** [paritytech/jsonrpsee#551]
I need to start two rpc server on the same socket address, can I call server.start() twice such as this:
```rust
let server = HttpServerBuilder::default().build(listen_address).unwrap();
let rpc_impl_1 = RpcImpl1::new();
let rpc_impl_2 = RpcImpl2::new();

server.start(rpc_impl_1.into_rpc());
server.start(rpc_impl_2.into_rpc());
```

**Comment by dvdplm** [comment]
You need to merge the two `RpcModule`s into one and then hand that off to the server, see for instance [this test](https://github.com/paritytech/jsonrpsee/blob/ff3337b107bf29bef6067164c20c6a0b0b5bdc75/utils/src/server/rpc_module.rs#L747).

**Comment by KaoImin** [comment]
> You need to merge the two `RpcModule`s into one and then hand that off to the server, see for instance [this test](https://github.com/paritytech/jsonrpsee/blob/ff3337b107bf29bef6067164c20c6a0b0b5bdc75/utils/src/server/rpc_module.rs#L747).

However, the RPC method is generated by the proc-macro `#[rpc(server)]`, which seems difficult to merge.

**Comment by niklasad1** [comment]
It's possible for instance you can do it like [this](https://github.com/paritytech/substrate/blob/7898fcc409f364716ca5fcd61100df643274f296/bin/node-template/node/src/rpc.rs#L45-#L50)

Perhaps we could provide a macro for this

**Comment by KaoImin** [comment]
> It's possible for instance you can do it like [this](https://github.com/paritytech/substrate/blob/7898fcc409f364716ca5fcd61100df643274f296/bin/node-template/node/src/rpc.rs#L45-#L50)
> 
> Perhaps we could provide a macro for this

That is what I am seeking.

**Comment by niklasad1** [comment]
I regard your response as it resolved your question, so closing.

Otherwise feel free to reopen the issue.
