### ISSUE TITLE
[clients]: inconsitent behaviour w.r.t to default port number in URL

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#554]
The clients act different when parsing the `URL/URI` whereas:

- HTTP Client - uses `url::Url::parse` which provides the default port number if missing
- WS Client - uses `http::Uri` which doesn't provide the default port number if missing but https://github.com/hyperium/http/issues/509 blocks us from applying this ourselves because the URL might get rejected if a bad port number such as `-99` was entered

The reason why we use `http::Uri` in the WsClient is because it supports relative URIs that is needed to handle redirections.

**Comment by dvdplm** [comment]
So this issue implies switching to `http::Uri` for websockets as well then?

**Comment by niklasad1** [comment]
Ideally jsonrpsee would provide the default port number if missing but that requires https://github.com/hyperium/http/issues/509 to fixed.

Thus, I don't know but we could use `url` and use https://docs.rs/url/2.2.2/url/struct.Url.html#method.port instead of https://docs.rs/url/2.2.2/url/struct.Url.html#method.port_or_known_default for consistent behaviour

**Comment by dvdplm** [comment]
Imo consistency trumps the usefulness of providing a default port.

**Comment by niklasad1** [comment]
Closed by #545
