### ISSUE TITLE
Unable to discern address in use error

### ISSUE THREAD

**Issue by maciejhirsz** [paritytech/jsonrpsee#562]
When the JSON-RPC address is in use, [Substrate retries with a random port](https://github.com/paritytech/substrate/blob/7db0768a85dc36a3f2a44d042b32f3715c00a90d/client/service/src/lib.rs#L353-L355). This work fine with `jsonrpc`, but we unfortunately erase std::io errors type with anyhow.

We should have a new error variant(s) just for `AddressInUse | PermissionDenied`. Bonus points if we can either not consume the builder, or return the builder in the error for easy retries. Alternatively support the strategy of trying random port directly into jsonrpsee.

**Comment by niklasad1** [comment]
right, didn't think about this....

**Comment by maciejhirsz** [comment]
Solved by #567.
