### ISSUE TITLE
Merge multiple `RpcModule`s at once

### ISSUE THREAD

**Issue by dvdplm** [paritytech/jsonrpsee#565]
Consider:

```rust
let foo: RpcModule<FooContext> = build_foo_rpc();
let bar: RpcModule<BarContext> = build_bar_rpc();
let baz: RpcModule<BazContext> = build_baz_rpc();
let mut the_one = RpcModule::<()>::new();
the_one.merge(foo)?;
the_one.merge(bar)?;
the_one.merge(baz)?;
the_one
```

It's a bit repetitive. It'd be nice to have `the_one.extend(&[foo, bar, baz])` or similar to mash them all together in one go. See [this](https://github.com/paritytech/substrate/blob/7b254bd1f60f6c6fe83ca1d6ada02b784f04188f/client/service/src/builder.rs#L641-L650) for a real world example.

**Comment by niklasad1** [comment]
Intentionally closed @dvdplm?!

**Comment by dvdplm** [comment]
Yes, intentional. I had a stab at this and it's not trivial to have a `merge_multi()` method that takes a collection of heterogeneous `RpcModule<T>` (different `T`s). We'd have to either do it in a macro or build the collection with a `.map(RpcModule::remove_context)` or implement `merge_multi` on tuples. All bad options that needs more code than I think this feature is worth.

Am I wrong?

**Comment by niklasad1** [comment]
ah, sounds reasonable I just didn't understand why :)

I have also thought about a macro to `merge` modules but we would need to unwrap() inside it to work I think
