### ISSUE TITLE
Add a way to customize `SubscriptionId` generation

### ISSUE THREAD

**Issue by librelois** [paritytech/jsonrpsee#599]
I started to migrate the codebase of [frontier](https://github.com/paritytech/frontier) on jsonrpsee based on the branch `polkadot-jsonrpsee-v0.9.13` and I notice that jsonrpsee lacks an essential feature that makes it impossible to use it in frontier: the possibility to customize the way to generate `SubscriptionId`.

Indeed, frontier must reproduce the ethereum RPC api with accuracy, this includes providing SubscriptionId in string form with 16 bytes in hexadecimal representation prefixed by `"0x"`.

Frontier currently uses jsonrpc, which allows custom generation of subscription ids with the `with_id_provider` function: https://github.com/paritytech/jsonrpc/blob/609d7a6cc160742d035510fa89fb424ccf077660/pubsub/src/manager.rs#L154

**Comment by niklasad1** [comment]
fair enough then, we should support this.

//cc @maciejhirsz 

Should we simply have another param to `register_subscription` that takes a closure that generates a `String` or `u64`?
However, it will be hard to solve "nice" in the proc macro... I guess

Thoughts?

**Comment by maciejhirsz** [comment]
Do we need to touch proc macros with this? I'd think this is more of a server config stuff. And yeah, a closure (generator) that yields a new `SubscriptionId` should suffice.

**Comment by niklasad1** [comment]
`SubscriptionId` generator is in the `RpcModule` so it's not possible to make this configuration based on the server itself. However, we could include it the `callback closure` similar to what we did for `MaxPayloadSize a.k.a MethodSink` that should work then no proc macro stuff needs changing....

any other ideas?

**Comment by niklasad1** [comment]
Closed by #604
