### ISSUE TITLE
Need to be able to group generated APIs together and answer requests

### ISSUE THREAD

**Issue by tomaka** [paritytech/jsonrpsee#6]
When generating multiple APIs, we need to be able to group them together in order to call `next_request` once.

**Comment by tomaka** [comment]
The main question is: how would it look like to use such a grouping thing?
We could ask the user to create another enum that groups all the sub-enums together, or we could provide some sort `select!`-like macro.

**Comment by dvdplm** [comment]
Closing as stale (and resolved by using multiple `RpcModule`s and their `merge()` method).
