### ISSUE TITLE
ci: expose benchmark results from internal Gitlab and plot in GH-pages

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#600]
After https://github.com/paritytech/jsonrpsee/pull/534 was merged the daily benchmarks are executed on Gitlab and those results are not publicly accessible anymore.

There is a pending issue to push these raw results to the `gh-pages` branch and hopefully make it visualize-able on GitHub pages.

**Comment by dvdplm** [comment]
> There is a pending issue to push these raw results to the `gh-pages` branch and hopefully make it visualize-able on GitHub pages.

Do you have a link for this I can subscribe to?

**Comment by niklasad1** [comment]
Closed by https://github.com/paritytech/jsonrpsee/pull/603
