### ISSUE TITLE
[proc_macros]: `_` as ident doesn't work

### ISSUE THREAD

**Issue by driftluo** [paritytech/jsonrpsee#609]
```
use jsonrpsee_proc_macros::rpc;
use bytes::Bytes;

#[rpc(server)]
pub trait ARpc {

    #[method(name = "a")]
    async fn a(&self, _: Bytes);
}
```
will report:
```
error: custom attribute panicked
   |
14 | #[rpc(server)]
   | ^^^^^^^^^^^^^^
   |
   = help: message: Identifier in signature must be an ident
```

**Comment by niklasad1** [comment]
Indeed, `_: Bytes` as identifier doesn't work but `_a: Bytes` works.

//cc @maciejhirsz

**Comment by dvdplm** [comment]
@driftluo Thank you for the report. We landed on not supporting `_` as method argument name but improved the error handling to explain to users what happened a bit better.

**Comment by niklasad1** [comment]
FYI, because the servers currently support both the params to be passed as `array` or `JSON object` these identifiers are used to generate named fields in the JSON objects.
