### ISSUE TITLE
RPC optimization for scaling

### ISSUE THREAD

**Issue by Maharacha** [paritytech/jsonrpsee#610]
We (Dwellir) are running RPC services, currently on Kusama but on Polkadot as well very soon. We are in the writing of a proposal where we want to optimize the RPC code since it scales very badly. E.g. on Kusama we currently run 14 nodes with a container solution to fully make use of the CPU, since it seems like the code is single threaded. With a better, optimized code, it should be possible to run only 1 node that makes use of all the cores. Now, we just found out this repo...

Would you say that the code you are working on here already fixes this problem?

**Comment by dvdplm** [comment]
Both `jsonrpc` and `jsonrpsee` use multiple CPUs, as do most code substrate that actually does the work. I'm sure there's plenty of room for optimization both in `jsonrpsee` and `substrate`/`polkadot` and that's an on-going task for several teams.

I'm curious to hear more about your performance issues though. Do you have stats and metrics or even benchmarks you can share? Which RPC calls are slow in your experience?

**Comment by Maharacha** [comment]
We had an issue while we were investigating this
https://github.com/paritytech/polkadot/issues/4064

But we are not sure what is the bottleneck in the code, that would be the first step in the project, to do analysis to find it. We saw a tendency that it was using only one CPU, but it could be something totally different.

The problem was that one node could not handle more than 20-30 connections before it got choked, while the machine was basically idling. When we run multiple polkadot-services on the same machines it works like a charm. Like I said we are now running 14 containers on that machine, with load balancing in the front.
One problem with this is that each container needs its own database, which of course doesn't scale well. We have temporarily solved this by making use of the overlay filesystem so that the containers can share already written data. But the long term solutions would be to make sure the polkadot-service itself can handle more connections.

It would save us a lot of money, since all RPC-providers have this problem, and some of them might even run this in the cloud making it super expensive.

**Comment by Maharacha** [comment]
> Which RPC calls are slow in your experience?
The different pages on polkadot.js, the Explorer-page is quite good, since it shows the time for each block to get returned from the RPC-node (should ideally be 6 seconds). This could take up to 2 minutes when the node was choked. However, the node itself was always in sync with the latest block.

**Comment by maciejhirsz** [comment]
Just looking at network traffic on explorer it looks like there is a lot of events sent over via subscribtion (`state_storage` notifications specifically). I'd be surprised if `jsonrpc` or `jsonrpsee` were at fault here, but we should revisit how subscriptions are done and look at the code that produces the notifications in substrate.

My hunch would be that either the individual subscribers are not put on separate tokio tasks, or (more likely I reckon) they need to access shared state and there is a mutex everything has to go through, which would limit it 1 core at a time (even if it's a different core at any given time).

**Comment by dvdplm** [comment]
> My hunch would be that either the individual subscribers are not put on separate tokio tasks, or (more likely I reckon) they need to access shared state and there is a mutex everything has to go through, which would limit it 1 core at a time (even if it's a different core at any given time).

Possibly both of these things.

@Maharacha Feel free to open an issue on the substrate or polkadot repos, but be aware that they will most likely ask you the same questions we ask here:

- what calls are slow
- how slow is "slow"
- a script or a code snippet to reproduce your data
- a complete description of the environment (hardware used, description of the full stack etc)

Given hard data and a way to reproduce the problem I'm confident that we'll be able to get it sorted fairly quickly.

**Comment by Maharacha** [comment]
Thanks for all the answers! We will continue with the proposal to start investigating this.
