### ISSUE TITLE
how  can i  retun  a custom response header?

### ISSUE THREAD

**Issue by DavidChild** [paritytech/jsonrpsee#628]
Now I want to add custom HTTP header information in the reponse structure after the request and return it to the client .
Or how can I solve the cross domain problem through web requests
![image](https://user-images.githubusercontent.com/18735238/147324601-013aa3a7-7026-4df2-921b-04f39ded8ac2.png)

However, I still encounter the same problem in the way I operate on the document, as shown in the following code

![image](https://user-images.githubusercontent.com/18735238/147324742-3b1b3f92-2c57-4b44-a7b3-ac2969827ca5.png)

**Comment by maciejhirsz** [comment]
We don't have custom headers support yet, but we do have CORS support: https://docs.rs/jsonrpc-http-server/latest/jsonrpc_http_server/struct.ServerBuilder.html#method.cors

**Comment by jsdw** [comment]
@DavidChild we've been working on a fix to improve the CORS support here: https://github.com/paritytech/jsonrpsee/pull/637

I wonder if you'd be able to have a go using that branch and check that your issue is resolved with it?

**Comment by niklasad1** [comment]
I belive #637 will fix cross domain web requests, if not feel free to reopen this issues.
