### ISSUE TITLE
WS to HTTP redirection doesn't seem to be handle correctly

### ISSUE THREAD

**Issue by paulormart** [paritytech/jsonrpsee#638]
@paulormart 

please open an issue in `jsonrpsee` but the issue is that you got a HTTP redirection there... to a HTTP endpoint

```
target: Target { sockaddrs: [104.26.8.125:80, 104.26.9.125:80, 172.67.71.26:80, [2606:4700:20::681a:97d]:80, [2606:4700:20::ac43:471a]:80, [2606:4700:20::681a:87d]:80], host: "rpc.polkadot.io", host_header: "rpc.polkadot.io:80", _mode: Plain, path_and_query: "/" }
2022-01-05T15:32:34.132404Z DEBUG jsonrpsee_client_transport::ws: Connecting to target: Target { sockaddrs: [104.26.8.125:80, 104.26.9.125:80, 172.67.71.26:80, [2606:4700:20::681a:97d]:80, [2606:4700:20::ac43:471a]:80, [2606:4700:20::681a:87d]:80], host: "rpc.polkadot.io", host_header: "rpc.polkadot.io:80", _mode: Plain, path_and_query: "/" }
2022-01-05T15:32:34.266608Z DEBUG jsonrpsee_client_transport::ws: Redirection: status_code: 301, location: https://rpc.polkadot.io/
thread 'main' panicked at 'Some("https")', client/transport/src/ws/mod.rs:440:17
```

Thus, meanwhile use `wss://rpc.polkadot.io:443` if that's alright for you.

_Originally posted by @niklasad1 in https://github.com/paritytech/subxt/issues/384#issuecomment-1005824575_

**Comment by paulormart** [comment]
Thanks for reviewing this @niklasad1 

If `wss://rpc.polkadot.io:443` is used from the `subxt` side we get this error `Error: Rpc(Transport(Invalid URL: URL scheme not supported, expects 'ws'))`

**Comment by paulormart** [comment]
Ok got it. `client-ws-transport` feature was missing from the client library.

Cargo file should specify it like `jsonrpsee = { version = "0.7.0", features = ["macros", "ws-client", "http-client", "client-ws-transport"] }`

**Comment by niklasad1** [comment]
The redirection is still an issue but I don't think there is anything we can do beside print a better error message in the client.

> Ok got it. client-ws-transport feature was missing from the client library.

good catch, it's a bug the ws-client crate should expose that feature but you can solve it like that too :)
