### ISSUE TITLE
Option for rpc_api macro to build client functions with positional params

### ISSUE THREAD

**Issue by jimpo** [paritytech/jsonrpsee#65]
Some RPC servers (like the old [Parity JSONRPC one](https://github.com/paritytech/jsonrpc)) do not accept requests with params provided by name (ie. as a JSON object). It would be nice to be able to build a compatible client using `rpc_api`. Currently, if an RPC method takes parameters, `rpc_api` will build a calling function that passes arguments by name, not by position.

Perhaps the RPC API struct (defined with the macro) should be instantiable with an options argument including `disable_params_by_name: bool`. Or an new "rpc(disable_params_by_name)" macro attribute, but that seems bad because it's part of the server implementation, not really part of the RPC API itself.

**Comment by tomaka** [comment]
I'm really not satisfied with how the `rpc_api!` macro is designed at the moment.
The `disable_params_by_name` suggestion is probably the first in a list of hacks that we would have to add in order to bypass short-comings in the design.

**Comment by niklasad1** [comment]
Closed by #94
