### ISSUE TITLE
Client request response parse error

### ISSUE THREAD

**Issue by boyswan** [paritytech/jsonrpsee#653]
Every RPC request is failing with
`ParseError(Error("data did not match any variant of untagged enum Id", line: 1, column: 47))`

Example:
```rust
let client = HttpClientBuilder::default()
    .build("https://kusama-rpc.polkadot.io:443")
    .unwrap();
let response: String = client.request("system_chain", None).await.unwrap();
// fails
```

The data is being returned in the actual response:
`Ok(Object({"jsonrpc": String("2.0"), "result": String("Development"), "id": Number(0)}))`

**Comment by niklasad1** [comment]
Hey @boyswan 

That should work, have you enabled `--feature arbitrary-precision` on serde_json by any chance?
See https://github.com/paritytech/jsonrpsee/issues/480  for futher info
