### ISSUE TITLE
[examples]: add resource limiting example.

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#672]
Resource limiting were introduced for quite a long time a go and we should have an example that demonstrates this.

**Comment by charleschege** [comment]
I have just encountered this issue an example would be great. Currently using the format `resources("io" = 0, "mem" = 0)`
```
#[method(name = "getFoo", resources("io" = 0, "mem" = 0), aliases = ["getFoo"], )]
    async fn get_foo(
```
which results to the error 
```
Error: Resource name `io` not found for method `proxy_getFoo`
```
Any ideas on the best way to implement or solve this. It stems from the issue 
```
2022-10-27T08:58:46.082299Z ERROR method_call{method=getFoo}: jsonrpsee_core::server::helpers: Error serializing response: Error("Memory capacity exceeded", line: 0, column: 0)
```

**Comment by niklasad1** [comment]
1.
> I have just encountered this issue an example would be great. Currently using the format `resources("io" = 0, "mem" = 0)`
```
#[method(name = "getFoo", resources("io" = 0, "mem" = 0), aliases = ["getFoo"], )]
    async fn get_foo(
```
which results to the error 
```
Error: Resource name `io` not found for method `proxy_getFoo`
```

This is most likely some naming error such as the you expect a namespace where it is missing. You can try to call "getFoo" without the namespace "proxy_getFoo".

2.
> Any ideas on the best way to implement or solve this. It stems from the issue 
```
2022-10-27T08:58:46.082299Z ERROR method_call{method=getFoo}: jsonrpsee_core::server::helpers: Error serializing response: Error("Memory capacity exceeded", line: 0, column: 0)
```

That has nothing to do with "resource limiting" which is something where you can add your own abstract resources that is checked on each call but yeah a bit confusing.

The error you are receiving is that the default hardcoded max response size of a RPC call was exceeded  you can configure them by [ServerBuilder::max_request_body_size](https://docs.rs/jsonrpsee-ws-server/0.15.1/jsonrpsee_ws_server/struct.WsServerBuilder.html#method.max_request_body_size) and [ServerBuilder::max_response_body_size](https://docs.rs/jsonrpsee-ws-server/0.15.1/jsonrpsee_ws_server/struct.WsServerBuilder.html#method.max_response_body_size)

**Comment by niklasad1** [comment]
Resource limiting is not supported anymore
