### ISSUE TITLE
Allow trait bounds to be overridden in macro

### ISSUE THREAD

**Issue by jsdw** [paritytech/jsonrpsee#696]
First off, apologies if this is wrong; I haven't spent long digging into the macro code here!

So, currently we can generate a client impl using the proc macro like so:

```
#[rpc(client, namespace = "foo")]
pub trait MyRpc<T> {
    #[method(name = "bar")]
    fn method(&self) -> RpcResult<T>;
}
```

I believe this generates something like an `trait MyRpcClient<T>: ClientT where T: Send + Sync + 'static` trait, and an impl for it that means the RPC `Client` impls these methods (very cool btw!).

However, in some cases this general rule of applying `Send + Sync + 'static` to all type params is unnecessarily restrictive. Take the following example:

```
trait Config {
    type Hash: Send + Sync + 'static;
}

#[rpc(client, namespace = "foo")]
pub trait MyRpc<T: Config> {
    #[method(name = "bar")]
    fn method(&self) -> RpcResult<T::Hash>;
}
```

This generates something like `trait MyRpcClient<T>: ClientT where T: Send + Sync + 'static + Config`, but here `T` does not need to be `Send + Sync + 'static` since it's not actually returned or passed in anywhere (we only care about `T::Hash`).

This is quite a common issue in derives too, for instance if we take this struct:

```
#[derive(Clone)]
struct Foo<T> {
    marker: std::marker::PhantomData<T>
}
```

The generated `Clone` impl is something like `impl <T> Clone for Foo<T> where T: Clone {..}`, which is unnecessary since T really doesn't need to be cloneable (it's not instantiated anywhere).

A common solution is to allow people an escape hatch to override the automatically applied trait bounds. The `derivative` library provides this for common traits, so we could impl Clone for all `Foo<T>`'s like so:

```
#[derive(Derivative)]
#[derivative(Clone(bound = ""))]
struct Foo<T> {
    marker: std::marker::PhantomData<T>
}
```

This generates an impl more like `impl <T> Clone for Foo<T> {..}` (we override the Clone bounds to be nothing).

Serde has a similar feature:

```
#[derive(Serialize)]
#[derde(bound = "")]
struct Foo<T> {
    marker: std::marker::PhantomData<T>
}
```

Again, we can manually set the bound to something like "T: MyTrait", or in our case, nothing ("").

Perhaps it would be useful to provide a similar "escape hatch" in jsonrpsee? With such a feature, the earlier example could be made to work with something like:

```
trait Config {
    type Hash: Send + Sync + 'static;
}

#[rpc(client, namespace = "foo", client_bound = "")]
pub trait MyRpc<T: Config> {
    #[method(name = "bar")]
    fn method(&self) -> RpcResult<T::Hash>;
}
```

It would need a little thought;
- does `client_bounds` override _all_ bounds that would be applied, so that they all need to be manual? In this case we might need eg `client_bound = "T::Hash: Serialize + Deserialize"` or something?
- would we need `client_bound` and `server_bound` to allow overriding each?

**Comment by jsdw** [comment]
Another thought; I believe `jsonrpsee` already scane through the type params used in function signatures to apply the correct bounds for each in the where clause (though again, maybe I'm understanding this wrong at the mo and this can all be ignored too :)).

So I wonder what would happen if it didn't autoamtically add any trait bounds based on the generic params provided at the top?

So for example, this:

```
trait Config {
    type Hash: Send + Sync + 'static;
}

#[rpc(client, namespace = "foo", client_bound = "")]
pub trait MyRpc<T: Config> {
    #[method(name = "bar")]
    fn method(&self) -> RpcResult<T::Hash>;
}
```

Would lead to a bound like `T::Hash: Send + Sync + 'static + Serialize` being added, but since `T` isn't actually passed in or returned directly, it wouldn't get any bounds itself. Perhaps if we were more "precise" with the trait bounds we need in this way, we don't need an escape hatch at all?

**Comment by niklasad1** [comment]
> Would lead to a bound like T::Hash: Send + Sync + 'static + Serialize being added, but since T isn't actually passed in or returned directly, it wouldn't get any bounds itself. Perhaps if we were more "precise" with the trait bounds we need in this way, we don't need an escape hatch at all?

Yupp, we did provide the trait bounds such that everyone didn't need provide these trait bounds themselves because for convenience but as you said it's not very flexible and won't work properly if you just need to trait bound for some associated type or something and not for the entire trait.

Thus, we could just kill the generated trait bounds and have the users deal with the themselves. It would reduce lots of code for us so WDYT?

//cc @maciejhirsz @dvdplm

**Comment by jsdw** [comment]
Rather than killing all of the trait bounds, I was more thinking that we could either:

1. Be more precise with our trait bounds, only applying as needed based on generic params on methods (this may be hard or not depending on what jsonrpsee already does!)
2. Leave the trait bounds as is, unless a user provides an escape clause like an attr, for example something like `#[rpc(client_bounds = "Bar: Deserialize + 'static", server_bounds = "Foo: Serialize")]`, and then perhaps remove all generated bounds and leave it entirely up to the user.

Just a thought anyway :)

**Comment by niklasad1** [comment]
I like option 2) let's try to implement it

**Comment by dvdplm** [comment]
Yes, we've seen versions of the same thing pop up in `parity-scale-info`, `scale-info` and now here. I like solution 2 as well.
