### ISSUE TITLE
Consider extending the parameters of Middleware::on_call

### ISSUE THREAD

**Issue by ljedrz** [paritytech/jsonrpsee#699]
snarkOS could use the ability to log the source and possibly some of the header of the RPC requests it receives: https://github.com/AleoHQ/snarkOS/issues/1628; I think this could be achieved by extending the parameters of `Middleware::on_call`, but I'm open to other options.

If I didn't miss anything in my partial implementation of a [PR addressing the linked issue](https://github.com/AleoHQ/snarkOS/pull/1635), this is currently not supported.

I know that there is a `DEBUG` log turned on by default, but it was too verbose and I think it only contained information on the response (which was also truncated if it was deemed too long), so we silenced that one.

Possibly related existing issues: https://github.com/paritytech/jsonrpsee/issues/450, https://github.com/paritytech/jsonrpsee/issues/487.

**Comment by dvdplm** [comment]
@ljedrz Thank you for the report. One question: when you say "source", what do you have in mind exactly? Do you mean the IP of the host sending the request?

**Comment by dvdplm** [comment]
@maciejhirsz I think we talked about adding this at some point, right?

**Comment by maciejhirsz** [comment]
Yep, we can expose IP and headers in middleware.

**Comment by 666lcz** [comment]
> Yep, we can expose IP and headers in middleware.

Hi @maciejhirsz , do you have any ETA for supporting this? We are trying to implement some sort of rate-limiting by IP address. Ty!

**Comment by niklasad1** [comment]
Closed by #793
