### ISSUE TITLE
Enable selective spam prevention

### ISSUE THREAD

**Issue by ljedrz** [paritytech/jsonrpsee#700]
If I'm not mistaken, there is currently no way of rejecting requests from a single address in case it has been sending too many of them. I know that the list of allowed hosts can be restricted, but this is too limiting if the server is to be publicly open.

There are multiple ways in which this could be achieved, some of which wouldn't even cause any API breakage, e.g.:

- introduce a new method like `HttpServerBuilder::max_request_body_size`, e.g. `::minimum_time_between_requests` that - if enabled - would automatically enforce a minimum `Duration` interval between requests from a given host; the value passed to it could be optional, making it unused by default
- provide `Middleware` with a new provided method, e.g. `::should_request_be_rejected` that would be called after `::on_request`, have the requester's IP and the request's `Instant` (collected from `::on_request`) as parameters, and terminate `process_validated_request` at that point if it returns `true` (and the default impl would return `false`); this could allow the users to utilize it in tandem with e.g. an IP blacklist possibly shared between `Middleware` and some other external object
- I've also considered the option of extending `AccessControlBuilder`, but that one would be tricky, as it would not have access to an auto-updated banlist unless it was some `static`

Please let me know if I have missed an existing way of achieving this. Otherwise, if any of the ones I listed would be preferable (especially the second one, which would be trivial to implement), I'd be happy to file a relevant PR.

**Comment by ljedrz** [comment]
Understood; feel free to close the issue (and label it as `wontfix` or equivalent for easier future discoverability) since there's maintainer consensus on this.

**Comment by dvdplm** [comment]
Thank you for understanding, and keep the ideas coming. :)
