### ISSUE TITLE
can namespace and method name be joined by . intead of _

### ISSUE THREAD

**Issue by hunjixin** [paritytech/jsonrpsee#704]

**Comment by niklasad1** [comment]
Currently no but you do it yourself by skipping the `namespace` on RPC API trait:

```rust
#[rpc(server, client)]
pub trait Rpc {
	#[method(name = "myname.period")]
	async fn example(&self) -> Result<String, Error>;
}
```

**Comment by hunjixin** [comment]
> Currently no but you can do it yourself by skipping the `namespace` on RPC API trait:
> 
> ```rust
> #[rpc(server, client)]
> pub trait Rpc {
> 	#[method(name = "myname.period")]
> 	async fn example(&self) -> Result<String, Error>;
> }
> ```

yes i just do like this
