### ISSUE TITLE
Can user get `SubscriptionId` from `SubscriptionSink`?

### ISSUE THREAD

**Issue by driftluo** [paritytech/jsonrpsee#709]
not all subscription and unsubscription with the single method, sometimes unsubscription with the `SubscriptionId`, but now, user unable to construct a relationship between `SubscriptionSink` and `SubscriptionId`

**Comment by dvdplm** [comment]
Hmm, I don't quite understand what you mean. Can you elaborate? Do you have some code to show us?

**Comment by niklasad1** [comment]
Hey @driftluo 

Currently the `SubscriptionId` kept private in the [SubscriptionSink](https://github.com/paritytech/jsonrpsee/blob/master/core/src/server/rpc_module.rs#L733).

As you have probably know [the subscription API](https://github.com/paritytech/jsonrpsee/blob/master/core/src/server/rpc_module.rs#L615-#L621) defines both a `subscription method` and `unsubscribe method` so why would need to know the subscriptionID in context for the servers?

So yeah, please elaborate what you are trying to do with an example...

**Comment by driftluo** [comment]
> As you have probably know [the subscription API](https://github.com/paritytech/jsonrpsee/blob/master/core/src/server/rpc_module.rs#L615-#L621) defines both a subscription method and unsubscribe method so why would need to know the subscriptionID in context for the servers?

I know this defines two methods for both subscribing and unsubscribing, but when implementing web3's `eth_subscribe` and `eth_unsubscribe`, the id provided by `eth_unsubscribe` does not correspond to the sink, i.e. the method cannot be implemented

**Comment by niklasad1** [comment]
Right you have to configure the subscriptionID generation to be according to the `ethereum specification` by default we generate random integers.

See https://github.com/paritytech/jsonrpsee/blob/master/ws-server/src/server.rs#L807-#L830, there is a trait IdProvider that you can implement yourself for this i.e, ethereum requires the subscriptionID to be a hexstring of 12 bytes IIRC.

Also make sure that you override the notification method in the subscriptions by:

```rust
#[subscription(name = "eth_subscribe" => "eth_subscription", unsubscribe = "eth_subscribe", item = String)]
fn eth_subscribe(&self) -> RpcResult<()>;
```

**Comment by driftluo** [comment]
The id provider is not enough, can the internal implementation of jsonrpsee guarantee that the ids assigned by the id provider will always generate the corresponding sink to the callback function?

For example：

If the connection is closed after the id provider is generated, and the sink corresponding to the id is not passed to the callback, then such a strong association is not guaranteed, which means that the unsubscribe will execute with an error instead of simply failing.

At the same time, the creation of subscriptions in a concurrent state does not guarantee a strong association between id and sink, which can also cause misalignment

If user can't get the id from the sink, it's hard to get this implementation exactly right

**Comment by driftluo** [comment]
After I read the source code, I found that this id correspondence is already being handled, so I don't need to correspond again when the server is implemented.

ref: 
https://github.com/paritytech/jsonrpsee/blob/b0f89485f35925e4a56d0776b9d4e116e88d8a4a/core/src/server/rpc_module.rs#L681
https://github.com/paritytech/jsonrpsee/blob/b0f89485f35925e4a56d0776b9d4e116e88d8a4a/core/src/server/rpc_module.rs#L644-L652

**Comment by niklasad1** [comment]
> @niklasad1 The id provider is not enough, can the internal implementation of jsonrpsee guarantee that the ids assigned by the id provider will always generate the corresponding sink pass to the callback function?

Yes, that is my understanding because the IdProvider is used to generate a new subscriptionID and SubscriptionSink per subscription/callback. So you shouldn't need to care about that the SubscriptionId at all.

> If the connection is closed after the id provider is generated, and the sink corresponding to the id is not passed to the callback, then such a strong association is not guaranteed, which means that the unsubscribe will execute with an error instead of simply failing.

As the actual is connection is coupled to the `SubscriptionSink` it will fail when actual connection gets closed because the `receiver` will be dropped by the connection. If that's occur you should get `Error::SubscriptionClosed` back.

**Comment by driftluo** [comment]
Thanks, I know these now
