### ISSUE TITLE
Huge regression in case of too many HTTP requests

### ISSUE THREAD

**Issue by librelois** [paritytech/jsonrpsee#716]
I tested the `http_concurrent_conn_calls` benchmark on a machine with 32 cores, and I see indeed a huge regression with jsonrpsee, about 98%!

I ran it in this order:

1. jsonrpsee master https://github.com/paritytech/jsonrpsee/commit/78055feb19dc95f53f6145aba606a253efe9f82a
2. jsonrpc

In 2. I observe a performance gain of 98% in `sync/512`, `sync/1024`, `async/512` and `async/1024`, similar performance in the other cases.

This means that jsonrpsee is twice as slow as jsonrpc in cases `sync/512`, `sync/1024`, `async/512` and `async/1024`.

**Comment by niklasad1** [comment]
Closed by #718, feel to try it out again @librelois 

A followup PR is coming soon where it will possible to configure to `backlog` in the HTTP server.
