### ISSUE TITLE
[rpc module]: add easy way to register subscription without accept/reject API

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#735]
https://github.com/paritytech/jsonrpsee/pull/728#issuecomment-1099133993

**Comment by jsdw** [comment]
Given the other stuff we're working on, I suspect that we'll just end up closing this and accepting that the accept() API will be useful and not worth trying to avoid (also being able to `pipe_from_stream` on the pending sink makes it more ergonomic already)

**Comment by lexnv** [comment]
Closed by: https://github.com/paritytech/jsonrpsee/pull/799
