### ISSUE TITLE
Current Examples don't seem to run

### ISSUE THREAD

**Issue by chokosabe** [paritytech/jsonrpsee#749]
Have tried running the WS-Client examples and been having dependency errors. Will open a pull request for any changes needed once done but putting this up here in case anyone else having issues as well

**Comment by niklasad1** [comment]
No, not really please try to remove your `Cargo.lock` otherwise in the future please add instructions how to reproduce the given issue.

**Comment by niklasad1** [comment]
@chokosabe can you explain how to reproduce this please?

Otherwise, I'll close it in a few days.

**Comment by chokosabe** [comment]
Please go ahead, I'll just raise a PR with any changes. Thanks

**Comment by niklasad1** [comment]
Closing as stale, looking forward to your PR
