### ISSUE TITLE
Getting Error when creating a wss client

### ISSUE THREAD

**Issue by chokosabe** [paritytech/jsonrpsee#751]
Gist to recreate:

https://gist.github.com/chokosabe/8598f42cc865ca7cb042aeaf8ba57ce0

Getting this error:

Invalid URL: No port number in URL (default port is not supported)

Have tried different combinations of adding the url with the port number

**Comment by niklasad1** [comment]
Your address format is wrong should be:

```rust 
let client = WsClientBuilder::default().build("wss://kusama-rpc.polkadot.io:443").await.unwrap();
```

**Comment by chokosabe** [comment]
I used this url from the unit tests as an example:

Trying with this url in the format you outlined above works. Trying it with a url in this format:

wss://domain-here/ws/v3/hash-here:443

Doesn't work and I get the error above. The parser that parses the url to obtain the port number doesn't work. You can probably try the example url above and will get the same thing.

**Comment by chokosabe** [comment]
Should probably be raised as a url parsing bug but would assume this would be one of the base case scenarios covered

**Comment by niklasad1** [comment]
alright I see but the format is also wrong unfortunately.

should be `wss://domain-here::443/ws/v3/hash-here`

the format is 

`abc://username:password@example.com:123/path/data?key=value&key2=value2#fragid` I hope this helps.

**Comment by chokosabe** [comment]
Yeah you are totally right on this. Thanks

**Comment by noisypigeon** [comment]
What if the URL does not have a port? Is there a default port I can provide to satisfy the constraint or is it possible to opt out of port.

I.e. wss://rpc.osmosis.zone/websocket
