### ISSUE TITLE
[http server]: health_api is rather confusing because it's not exclusive for `/health`

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#765]
https://github.com/paritytech/jsonrpsee/pull/763#discussion_r870142939

Additionally the API is quite easy to misuse if one passes in something like a path with `/` and similar.

**Comment by tarrencev** [comment]
I think it makes sense to allow arbitrary registration of get hooks. Kubernetes for example supports both a `ready` and `live` endpoint and a consumer might want to expose metrics through another path too.

**Comment by jsdw** [comment]
We're hoping that, now we support tower middleware on the HTTP server, that we might be able to remove this `/health` stuff from the core jsonrpsee code and provide it as a piece of middlewhere instead which might look like (names all made up):

```
let layer = ProxyGetRequestLayer::new("/health", "health_rpc_call");
```

And internally this middleware would look for matching HTTP requests and convert them into jsonrpc requests to pass on, and then strip the jsonrpsee outer stuff from the response too before passing it back.
