### ISSUE TITLE
Better error message on subscription limit

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/jsonrpsee#775]
As discovered in https://github.com/paritytech/substrate/issues/11460, when the limit of subscriptions is reached following error is returned to the client:
```
RPC call failed: ErrorObject { code: ServerError(-32604), message: "Server is busy, try again later", data: None }
```

The error isn't very descriptive, it took be a bit of time to figure out what resource was actually exceeded from error code. Something like "Reached limit for number of connections" would have saved me some time.

**Comment by niklasad1** [comment]
Fixed by #790
