### ISSUE TITLE
[ws client] Disconnect client when `Pong` frames are missing

### ISSUE THREAD

**Issue by lexnv** [paritytech/jsonrpsee#787]
PR #772 introduced the ability to `Ping` periodically the WS server, as a keep-alive alternative.

As an improvement, this can be extended to process `Pong` frames. If a `Pong` frame was not received
in a set interval (ie: time between two `Pings`, or user-driven interval), then the connection should
be dropped.

This adds extra complexity and should be taken into consideration if or when customers need such behavior.

**Comment by niklasad1** [comment]
Closed by #1258
