### ISSUE TITLE
Inspecting incoming request

### ISSUE THREAD

**Issue by wafflespeanut** [paritytech/jsonrpsee#811]
Currently it's not possible to inspect elements of an incoming HTTP request (like headers, URI, etc.) from within an RPC handler. Would it be possible to pass the hyper request object along with `Params` to handlers? Or, would it make sense to have `Params` as part of some custom `Request` object, which is then passed to the handlers?

**Comment by niklasad1** [comment]
Hey @wafflespeanut 

There is a pending PR for that https://github.com/paritytech/jsonrpsee/pull/793

I think that's what you need right?

**Comment by wafflespeanut** [comment]
If I'm not mistaken, that PR introduces this feature through the middleware right? I was wondering whether we could get this information from within the handlers.

**Comment by niklasad1** [comment]
Yeah, you are correct.

Ok, I see what you mean.

As `WS` and `HTTP` are a bit different we would want the `handlers` be have a clean abstraction for `JSON-RPC` calls and passing in the HTTP headers for the same `WS` connection seems a bit overkill.

Can you elaborate what's your usecase for having that in callbacks/handlers?

I think we are more or less happy to expose that inforamtion in the middleware and users that want to implement more sophisticated things such as user authentication, reject certain IP addresses can to that on top of the middleware via NGINX or something else.

**Comment by wafflespeanut** [comment]
> Can you elaborate what's your usecase for having that in callbacks/handlers?

We need to extract parameters from URLs matching a pattern. For context, I'm working on building a layer on top of bitcoin core and I'm using `jsonrpsee` for the RPC calls. Bitcoin (for some reason) [extracts parameters from URIs](https://github.com/bitcoin/bitcoin/blob/5bc10b39abbcb77638161902ccd1225139bc7cc0/src/wallet/rpc/util.cpp#L49) in RPC calls. I understand that this is not technically a clean thing to do (as they could've just used RPC parameters for doing that), but since they've gone down that route, I've no choice but to do the same.

If I could somehow get access to the underlying hyper `Request` object (or even `Uri` for that matter), it would be helpful. Or, if you think there's another way to approach this without making changes on a fork of `jsonrpsee`, then that'd be great as well :)

**Comment by niklasad1** [comment]
Ok, I guess you need functionality similar to https://docs.rs/jsonrpc-http-server/latest/jsonrpc_http_server/struct.ServerBuilder.html#method.rest_api then?

Would much nicer to have something like that than to leave that to the handler/callback itself to parse stuff from the URI.

We have been hoping to "get away" not to support that but if you are willing contribute and it's simple enough, then it should be okay to have I think.

/cc @jsdw @lexnv thoughts?

**Comment by wafflespeanut** [comment]
> Ok, I guess you need functionality similar to https://docs.rs/jsonrpc-http-server/latest/jsonrpc_http_server/struct.ServerBuilder.html#method.rest_api then?

REST -> RPC conversion won't be helpful, because I'll need access to URL in addition to the RPC parameters. Here's a cURL example:

```
curl -d '{"jsonrpc": "2.0", "id":"test", "method": "getnewaddress", "params": [] }' \
    -H 'content-type: application/json' http://127.0.0.1:18554/wallet/foo
```

Note that the request body is still following the RPC spec, but sent to a different endpoint instead of the root. I can't think of a way other than to get access to the underlying `Request` or `Uri` object through the handler.

**Comment by crystalin** [comment]
Adding my pov :)
This is also important on our side, currently there is no possibility to see http request and it prevents us from debugging most of our scenarios :(

**Comment by niklasad1** [comment]
https://github.com/paritytech/jsonrpsee/pull/831 will make it possible to inject your own middleware using tower.
So, it should be possible to enable whatever logging regarding the HTTP stuff you need and reject certain HTTP request based on your needs.

However, I don't think the Bitcoin usecase will work anyway where one needs to parse the params from the URI and pass it long to the "RPC handler/callback"

**Comment by crystalin** [comment]
Since the library provides the debug log for the response, shouldn't it also provide the debug log for the request by default ? (without having us to implement a middleware)

**Comment by niklasad1** [comment]
sure, let's add that

**Comment by niklasad1** [comment]
@crystalin those logs are changed to `TRACE` from `v0.15` and most of the super verbose stuff are removed, as the library is more battle tested now.

**Comment by jsdw** [comment]
Going to close this for now; We don't have any plans at current to inject the request into call/subscription handlers.

I do like the idea of being able to inject generic parameters into handlers, but it's not a feature that we can justify working on internally; contributions would be welcome though!

**Comment by niklasad1** [comment]
@wafflespeanut if you look at #859 you can define your own middleware similar to `ProxyGetRequest` to parse the `params` from the URI and pass "parsed params" to the rpc handler which I believe should be what you need.
