### ISSUE TITLE
Consider generalising middleware by passing state into every call

### ISSUE THREAD

**Issue by jsdw** [paritytech/jsonrpsee#816]
Currently the middleware is quite restrictive in what it enables with its passing of a copyable `Instant` from one method to another.

Is it worth generalising the way that we pass state between middleware calls to give people more flexibility?

Some thoughts on things one might want to do:

- Log the number of requests per connection (logs on disconnect)
- Log the average time taken per request on a connection
- Log the time that the connection was active for.

It might be that we don't need to extend middleware to support this kind of thing though?

See https://github.com/paritytech/jsonrpsee/pull/793#discussion_r913769995

**Comment by jsdw** [comment]
I added this to the 1.0 milestone because it's a breaking API change, but we may decide we don't want to do anything, and that's ok too!

**Comment by niklasad1** [comment]
So in general I like the idea but it's quite involved to implement as it requires major refactoring.

AFAIU it will work like this for each connection

```
// one state per connection
let state = <M as Middleware>::State::default();

middleware.on_connect(remote_addr, request.headers(), &mut state);

while active_connection {
   let single_or_batch = rx();

    // calls on `Middlware::on_call` and `Middleware::on_response`
   // this won't work because we can't borrow state mutable more than once
   // so we would need a mutex for that
   spawn(execute_call_async(middleware, &mut state, single_or_batch));
}

middleware.on_disconnect(remote_addr, &mut state);

```

**Comment by jsdw** [comment]
Going to close this; I don't think it's worth the time to dig into it if the current approach does what we need :)
