### ISSUE TITLE
Race condition in HTTP server: Mixed up result

### ISSUE THREAD

**Issue by crystalin** [paritytech/jsonrpsee#829]
We are still investigating but I open this issue as you might have some insight.

We are experiencing race condition using substrate v0.9.23 including JSONRPSee in Moonbeam. 
When performing multiple concurrent HTTP request from the same connection, some requests are answered with the data of other requests :(

Unfortunately the http server doesn't provide request logs, only the answers :/ so it is hard to verify with the logs.

I'll provide how to reproduce it quickly

**Comment by bkchr** [comment]
Cc @niklasad1 @jsdw

**Comment by crystalin** [comment]
Sorry, after further investigation, the issue happens in the the use of `batch payload` for JSONRPC. The [specs](https://www.jsonrpc.org/specification#batch) specify:
> The Response objects being returned from a batch call MAY be returned in any order within the Array

which wasn't handled properly by our partner.
