### ISSUE TITLE
Remove CORS support from Jsonrpsee and rely on tower middleware instead

### ISSUE THREAD

**Issue by jsdw** [paritytech/jsonrpsee#842]
Depends on us having #841.

Let's simplify Jsonrpsee by getting the CORS stuff out and relying on a pre-existing middleware instead.

When we do this we should have at least one example showing how to use the third party CORS middleware (eg this one; https://docs.rs/tower-http/latest/tower_http/cors/index.html)

**Comment by niklasad1** [comment]
@jsdw why was this removed from 1.0 milestone?
