### ISSUE TITLE
Release 0.16 and integrate into Substrate

### ISSUE THREAD

**Issue by jsdw** [paritytech/jsonrpsee#857]
Release the next version of jsonrpsee and update substrate/polkadot to make use of it.

When we're happy with this and such, we can aim at a 1.0 release.

Things to resolve before releasing:
- [x] https://github.com/paritytech/jsonrpsee/issues/920
- [x] https://github.com/paritytech/jsonrpsee/issues/909

**Comment by patrickkuo** [comment]
Great work on all the new changes! We are looking forward to all the new features especially middleware with tower service, and also the new server supports both http and WS connections.

It has been a while since last release, may I ask if you have a timeline for the 0.16 release?

**Comment by niklasad1** [comment]
Hey @patrickkuo thanks,

There are three things waiting to be merged (updated this issue)
I hope that it would max take two weeks until v0.16 is released.

**Comment by niklasad1** [comment]
v0.16 is released :)
