### ISSUE TITLE
Client subscription termination

### ISSUE THREAD

**Issue by ascjones** [paritytech/jsonrpsee#86]
Subscriptions in the shared client look like they never terminate:

https://github.com/paritytech/jsonrpsee/blob/master/src/client.rs#L239-L250

When the receiver yields `None`, (which I understand means the stream is exhausted) it returns `futures::pending!()`.

Also when using `while let status = subscription.next().await` we get the warning `irrefutable while-let pattern`.

Practically we break out of the loop when we receive the result we want e.g. https://github.com/paritytech/substrate-subxt/pull/58/files#diff-8776af0b15949a59471d9d5910b92db7R271. But what if the stream is closed (for whatever reason), presumably it will just hang?

**Comment by tomaka** [comment]
> which I understand means the stream is exhausted

Note that this should only ever if there's a logic error in the code, or if the background task crashes.

> Also when using while let status = subscription.next().await we get the warning irrefutable while-let pattern.

That's because `status` is an irrefutable pattern. `while let Some(status)` would work for instance.

> But what if the stream is closed (for whatever reason), presumably it will just hang?

Yes. It's an infinite loop, but the CPU usage will be low thanks to `pending!()`.

**Comment by ascjones** [comment]
> Yes. It's an infinite loop, but the CPU usage will be low thanks to pending!().
> Note that this should only ever if there's a logic error in the code, or if the background task crashes.

Cool so if I want to prevent my `async fn` containing the while loop from waiting indefinitely, then I should add a timeout?

> That's because status is an irrefutable pattern. while let Some(status) would work for instance.

Yeah I get this, but the signature of next `pub async fn next(&mut self) -> Notif` means that unless `Notif` itself (the type of the subscription message) is `Option` then we can't do this. 

It's fine it makes sense if it is intended to be an infinite loop anyway (subscriptions never end?). Just wanted to understand the reasoning behind the API, especially compared to `Stream::next` which does return an `Option`.

**Comment by tomaka** [comment]
> (subscriptions never end?)

They indeed never end, except if the client asks for it (which is done by dropping the `Subscription`) or if the connection to the server dies. I'm not sure how the latter is handled.
