### ISSUE TITLE
Avoid mandatory encoding into serde_json::Value for parameters 

### ISSUE THREAD

**Issue by jsdw** [paritytech/jsonrpsee#862]
Currently `client.request()`, `client.subscribe()` etc take in params that are `Option<ParamSer>`, which looks like:

```rust
#[derive(Serialize, Debug, Clone)]
#[serde(untagged)]
pub enum ParamsSer<'a> {
	/// Positional params (heap allocated).
	Array(Vec<JsonValue>),
	/// Positional params (slice).
	ArrayRef(&'a [JsonValue]),
	/// Params by name.
	Map(BTreeMap<&'a str, JsonValue>),
}
```

This makes encoding params to `serde_json::Value`'s mandatory, and said values are fairly allocation heavy.

How about we: 
1. Accept something like `Option<impl ToRpcParams>` instead of `Option<ParamSer>`on these methods.
2. Consider modifying `ToRpcParams` so that implementors can maximise their efficiency, so:
    - Have `to_rpc_params` take ownership of `self`; this can avoid unnecessary clones (eg if I already have the `Box<RawValue>` that it wants returned), and we only need to do this once, right? Also, you can impl it on a reference type if need be to take a reference.
    - Remove the supertrait of `Serialize`; let the implementor decide how it wants to provide the `Box<RawValue>`; it shouldn't need to be able to be serialized itself (again, if we already have a `RawValue` for instance). 
3. Impl `ToRpcParams` for `ParamSer` if we want to keep using it, orrrr (I think this is my preference, but could possibly be a separate issue:) build more efficient named and unnamed param encoding structs like follows (and update the `rpc_params!` macro to build unnamed params):

```rust
// Build named params:
pub struct NamedParamsBuilder(String);
// The finished, ready-to-go JSON:
pub struct NamedParams(String);

impl NamedParamsBuilder {
    pub fn new() -> Self {
        NamedParams("{".to_string())
    }
    pub fn insert<P: Serialize>(&mut self, name: &str, value: P) -> Result<(), Error> {
        self.0.extend(serde_json::to_string(name)?);
        self.0.push(':');
        self.0.push(value.serialize()?);
        Ok(())
    }
    pub fn build(self) -> NamedParams {
        self.0.push('}');
        NamedParams(self.0)
    }
}

impl ToRpcParams for NamedParams {
    fn to_rpc_params(self) {
        self.0.to_raw_value() // whatever the method to go from String to Box<RawValue> is.
    }
}

pub struct UnnamedParams(String);

impl UnnamedParams {
    // ... Similar sort of thing
}

// And now users can do something more efficient or whatever they prefer..

```

**Comment by niklasad1** [comment]
I think we should go ahead and introduce the `NamedParams`and `UnnamedParams` as you wrote above 

Then leave `ToRpcParams` as it is and only use it for the `server rpc module` as it is a trait for serialize a sequence as JSON array.

Maybe we need a marker trait of something for `Unnamed/Named params` or the builders could be the same type such as `Params(String)` because that the type needs to go in [here](https://github.com/paritytech/jsonrpsee/blob/master/types/src/request.rs#L120). 

The reason why is because we want ensure that the params is a valid JSON-RPC param i.e, a `array or map`

**Comment by jsdw** [comment]
One thing I want to be able to achieve here is that, if I have already serialized the params myself, that I can pass them to jsonrpsee without any additional allocation etc.

Ie right now I have to do this: https://github.com/paritytech/subxt/pull/634/files#diff-5ce128b6aa2d900cded027036a54849e2cd05f89e7d3920386a5ed16d7a35982R68

But I'd like to be able to take my `Box<RawValue>` and say to jsonrpsee "this is the correct structure; trust me".

So yeah, some kind of marker trait that can be implemented for `NamedParams` and `UnnamedParams`, but that also allows me to implement it for `MyParams(Box<RawValue>)` to just pass the already-encoded data over would be perfect.

The nice thing about this is that the trait enforces proper usage (ie only Named/UnnamedParams impl it) but also provides an escape hatch for others to implement this stuff on (and we can document the expectations of any implementation on the trait).
