### ISSUE TITLE
API versioning via HTTP header

### ISSUE THREAD

**Issue by Mirko-von-Leipzig** [paritytech/jsonrpsee#876]
We're exploring how we can efficiently version our JSON-RPC API. We want to serve multiple versions during deprecation periods to allow users to transition without breakage.

One approach is by utilising the HTTP `Accept` header and matching against something like `<application-name>/vX.Y.Z`. This has benefits over splitting versions over routes (e.g. `/rpc/v01` and `/rpc/v02`) in that proxies and SDKs don't have to worry about custom paths.

Initially I was thinking of having an `RpcModule` per version, but there isn't really a way of targetting a specific one, since they must both be merged into a server.

The only obvious way I could see is of doing this is by checking headers using hyper, manually parsing the request and then using `RpcModule::call` to handle it. Is there some other way I am missing?

**Comment by niklasad1** [comment]
You are right, that is not possible as the server API expects a `RpcModule` to start the server.

We got some new `middleware support (tower http)` where you can get access to HTTP request and implement a proxy yourself but it won't help in your case as you would want to call into two different `RpcModule's`.

> The only obvious way I could see is of doing this is by checking headers using hyper, manually parsing the request and then using RpcModule::call to handle it. Is there some other way I am missing?

Yes, I think that's the only way to implement it unfortunately.

I don't know whether it's possible to create another API that takes `fn start_with_modules(Vec<(RpcModule, Path)>)` instead of `fn start(impl Into<Methods>)` to support that.


```rust
/// Start the server with multiple APIs that are distinguished by `HTTP path`
/// 
fn start_with_modules(Vec<(RpcModule, Path)>) ...
```

//cc @jsdw @lexnv what do you guys think?

**Comment by Mirko-von-Leipzig** [comment]
We hacked something together in our fork [here](https://github.com/eqlabs/jsonrpsee/pull/1). Which I think looks similar to the api you mention above. We can submit it as an actual PR if you'd like, but that wasn't the intention - just something quick and dirty for us to get unstuck.

cc: @CHr15F0x

As a separate question (that I haven't thought about too hard) - would it ever make sense to have `From<RpcModule> for Service`? So that one could compose jsonrpsee services with whatever else one wants? Currently, jsonrpsee see's itself as the sole owner of a server, which makes sense in most scenario's until one wants.. many things.

**Comment by Mirko-von-Leipzig** [comment]
> It's quite bad that you have to fork jsonrpsee and it's quite out-of-date

We'll upgrade soon hopefully 👍

> Can you elaborate what you mean by `Service`? Is this something similar to `hyper::service_fn` or `tower::Service` you had in mind? Can you provide some example code how you want to use it?

I meant `tower::Service` but as I said - might just be a half-baked idea. If there was some mapping from `RpcModule` to `tower::Service` then we could easily compose it any tower middleware.

```rust
let mut module_v1 = RpcModule::new(context);
register_v1_methods(&mut module_v1);

let mut module_v2 = RpcModule::new(context);
register_v2_methods(&mut module_v2);

let v1_service = module_v1.into_service();
let v2_service = module_v2.into_service();

// Adapted from tower's Steer middleware example
let mut svc = Steer::new(
    // All services we route between
    vec![v1_service , v2_service ],
    // How we pick which service to send the request to
    |req: &Request<String>, _services: &[_]| {
        match req.uri().path() {
            // Replace with however one actually matches path prefixes..
            "/rpc/v1/" => 0,
            "/rpc/v2/" => 1,
            other => unimplemented!(),
        }
    },
);
```

**Comment by CHr15F0x** [comment]
We chose to fork to get some temporary yet working solution. I'll get back to you with some working example(s) based on `v0.15.1` :+1: .

**Comment by jsdw** [comment]
If you want to have all requests to "/rpc/v1/" serve "v1" methods, and all requests to "/rpc/v2/" to serve v2 methods, there are a few approaches I could picture involving writing a tower middleware to alter incoming requests. Here are a couple of thoughts:

## 1. Rewrite method names based on versions

Here, you'd attach a version to all method names internally, so you'd register methods/subscriptions like "foo_v1" and "bar_v2".

The middleware would then inspect the path and modify the body accordingly. You could look at the path or Accept header or whatever else and rewrite the method accordingly.

Eg, an incoming request with `Accept-Version: 2`  with a body `{ "jsonrpc": "2.0", "method": "foo" }` might then be transformed into a body like `{ "jsonrpc": "2.0", "method": "foo_v2" }`.

The upside of this approach is that you can use a header, or path, or whatever, to call into specifically named methods. 
The downside is that there is some overhead in rewriting the body like this.

## 2. include versions as part of the base method name

You could skip the rewrite part and just give methods version prefixes/suffixes? It wouldn't look as pretty, but functionally it would be simple to implement and keep track of.

**Comment by CHr15F0x** [comment]
The main issue we're having in pathfinder imo is not how to perform the versioning, be it via uri path or (custom) headers but rather the inability to manipulate the `Methods` passed into [`Server::start`](https://github.com/paritytech/jsonrpsee/blob/45c94a271d92294eda2a2c7d26477044a5983a25/server/src/server.rs#L108) via middleware.

**Comment by niklasad1** [comment]
@CHr15F0x 

The latest jsonrpsee stuff which isn't released yet though has support for custom middleware which works by implementing `tower::Service` so what @jsdw is suggesting is that you could hijack the http requestbased on the URI or custom header there and modify of the `method name` [similar to what do in the new ProxyGetRequest API](https://github.com/paritytech/jsonrpsee/blob/master/server/src/middleware/proxy_get_request.rs#L62-#L152)

That could indeed work but you have to separate the rpc methods by something prefix instead of the entire RpcModule

**Comment by CHr15F0x** [comment]
:+1: Yeah that would work without the need to fork.

**Comment by lexnv** [comment]
Would something similar to https://github.com/paritytech/substrate/issues/12961#issuecomment-1357457686 suffice for this?

The RPC implementation would need to namespace methods into `namespace = "v1"` and `namespace = "v2`.
Register all the methods to a single RPC server.

Then, we could add a middleware that changes:
- requests to `/rpc/v1` path with `methodA`
- into requests to `v1_method` 

@CHr15F0x would that also work for your use-case?

**Comment by niklasad1** [comment]
This is now supported by using jsonrpsee as service, [example here](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/jsonrpsee_as_service.rs)
