### ISSUE TITLE
Your Web Socket Examples Don't Work

### ISSUE THREAD

**Issue by HyperAlch** [paritytech/jsonrpsee#877]
I'm new to Rust, so please be patient.

Your Web Socket examples plain don't work. I'll be focusing on this one: https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/ws_pubsub_broadcast.rs

First off, these examples try to use a module path that doesn't exist:

```rust
use jsonrpsee::server::{RpcModule, ServerBuilder};
```

I figured out a fix by changing it to this:
```rust
use jsonrpsee::ws_server::{RpcModule, WsServerBuilder};
```
And my main issue is this code on line 95:

```rust
// In this example we don't care about doing shutdown so let's it run forever.
// You may use the `ServerHandle` to shut it down or manage it yourself.
tokio::spawn(handle.stopped());
```

I get an error: **"no method named `stopped` found for struct `WsServerHandle`"**

If I comment out this piece of code, the program works, but the server shuts down after all the clients have disconnected instead of staying open.

**Comment by niklasad1** [comment]
Hey @HyperAlch 

The examples on targets the `master branch` which isn't released yet on `crates.io` I think you are using `v0.15.1` right?

Then you could the examples under the `v0.15.1 tag`: https://github.com/paritytech/jsonrpsee/blob/v0.15.1/examples/examples/ws_pubsub_broadcast.rs

**Comment by HyperAlch** [comment]
That makes more sense. Thank you
