### ISSUE TITLE
Error returned by client.request is not very helpful

### ISSUE THREAD

**Issue by MichielHegemans** [paritytech/jsonrpsee#880]
Whenever a response returned by the `HttpClient::request` method is incorrect it seems to always produce something like the following error: `ParseError(Error("missing field `error`", line: 1, column: 5175))` which I guess is not untrue, since the field is indeed missing from the object, however I am not expecting it either so I am not sure where this comes from.

**Comment by niklasad1** [comment]
This a duplicated to https://github.com/paritytech/jsonrpsee/issues/298 and that was fixed recently on master. 

Thus, it's not released yet on crates.io but should done "soon"

**Comment by MichielHegemans** [comment]
Alright thanks a lot!
