### ISSUE TITLE
Client returns "invalid type: null, expected struct ErrorObject" if "error" field is set to null in the response

### ISSUE THREAD

**Issue by nchashch** [paritytech/jsonrpsee#888]
If the "error" field in the JSON RPC response object is null, like in
```json
{
  "result": 7199.9998414,
  "error": null,
  "id": "restclient"
}
```
the client returns the following error:
```
[src/main.rs:42] client.getbalance(None, None, None).await = Err(
    ParseError(
        Error("invalid type: null, expected struct ErrorObject", line: 1, column: 36),
    ),
)
```
I got this error, while trying to call Bitcoin's `getbalance` RPC.

The spec says: "[This member ["error"] MUST NOT exist if there was no error triggered during invocation.](https://www.jsonrpc.org/specification#response_object)" So I guess **technically** if there was no error and we set "error" to null, then the "error" field exists and the response object is invalid.

But it might make sense to treat this as a valid response anyway, especially considering that current behavior makes the library unusable for interacting with Bitcoin RPC or with RPC of any Altcoin that is a Bitcoin fork.

**Comment by niklasad1** [comment]
Hey @nchashch 

According the JSON-RPC v2 specification it clearly states:

> Either the result member or error member MUST be included, but both members MUST NOT be included.

So the response is not a valid JSON-RPC response according to the spec that's why you get this error.
I'm not familiar bitcoin RPC spec would be strange if it uses a custom flavor of the JSON-RPC.

I guess it's just the JSON-RPC server library that doesn't follow the JSON-RPC v2 specification correctly.

**Comment by niklasad1** [comment]
Closing this because it can't be interpreted as both `error`and `member` can co-exist according to the spec.

**Comment by Velnbur** [comment]
This is still a problem when you are communicating with `bitcoind` rpc as they return `"error": null`.

Is there any possible solution to this?

**Comment by jsdw** [comment]
I agree that we shouldn't bake any logic into `jsonrpsee` for this that is deliberately not spec compliant.

There is an open PR to fix this JSON-RPC stuff by the looks of it here: https://github.com/bitcoin/bitcoin/pull/27101. It has had recent activity, so at least there is hope that eventually they will be compliant.

Also worth noting that failing to interpretthe bitcoind response is fairly common amongst JSON-RPC libraries by the sounds of it eg https://github.com/bitcoin/bitcoin/issues/2960#issuecomment-166999099.

**Comment by Velnbur** [comment]
Sorry that I'm returning back to this discussion, but could we possibly have support of both protocol's versions as there not so many differences?

As a naїve solution it could be a compile time feature that "skips" these [line](https://github.com/paritytech/jsonrpsee/blob/3f16132f708909b5fecbf65e5dd8e2f7153f3f72/types/src/response.rs#L288).However I see a problem with cargo's dependencies resolving, when you will try to use both JSONRPC V1 and V2 in the same project

But also it could a separate client I think
