### ISSUE TITLE
[client]: batch request API is non-ergonomic

### ISSUE THREAD

**Issue by niklasad1** [paritytech/jsonrpsee#909]
After some debugging of batch requests it's hard to investigate why a certain batch request fails.
Currently, the assumption of the code is that all calls in the batch must succeed otherwise it's treated as an error.

For instance if one make a batch request with 100 calls inside, the 99 successful responses gets thrown away and not possible know that without using the logs, wireshark or something else. That lead me into the idea to return the entire batch regardless whether it was successful or not and let to user decide that.

It's not possible with the current API:

```rust
async fn batch_request<'a, R>(&self, batch: BatchRequestBuilder<'a>) -> Result<Vec<R>, Error>
	where
		R: DeserializeOwned + Default + Clone;
```

So I have two suggestions:

1. High-level API similar to current one but return `Vec<R, ErrorResponse>`
```rust
async fn batch_request<'a, R>(&self, batch: BatchRequestBuilder<'a>) -> Result<Vec<Result<R, ErrorResponse>, Error>
	where
		R: DeserializeOwned + Default + Clone;
```

it's then up to the user go through responses and it will be answered in the same order as inserted in the `BatchRequestBuilder`

2. Low-level API with JSON value 

```rust
enum DecodedResponse<'a> {
   Success(Response<'a, JsonValue>),
   Failed(ErrorResponse<'a>)
}

async fn batch_request<'a, R>(&self, batch: BatchRequestBuilder<'a>) -> Result<Vec<DecodedResponse>, Error>

```
the user has to deal with parsing the JsonValue to something else

**Comment by niklasad1** [comment]
it's a good to idea to have something simpler than what I suggested, something like `ResponseBatch` is good idea but I'm not sure about having both `result and error` in there because of 

> Either the result member or error member MUST be included, but both members MUST NOT be included.

thanks for the feedback

**Comment by jsdw** [comment]
Indeed, `ResponseBatch` doesn't really make sense to me offhand; the `Result<R, Error>` feels like it captures the essense of what we want quite well (it's either a value or some error)?

**Comment by niklasad1** [comment]
> One question I have is; what would R be if multiple different response types are expected back? Would the user be expected to declare an enum BatchResponse{ PossibleType1 {}, PossibleType2 {} }?

Yes, or `JsonValue/RawValue` do their own deserialization.

**Comment by niklasad1** [comment]
> I'd hope we could avoid that unsafe setting the vec length; possibly just by tweaking the code a bit so we push to the vec when results come back rather than need to know a positiion in it up front?

That's is tricky because the `ID` is not monotonically increasing i.e, it can wrap and an `ID` could be used twice and so on and we want ensure that the response is returned in the same order as the request.

I did a hack around it as follows (should be almost equivalent to previous variant):

```rust
		// TODO(niklasad1): best I could come up with without having the clone + default bounds.
		// NOTE: `ErrorObject` is placeholder and will be replaced in the loop below.
		let mut responses: Vec<_> = Vec::with_capacity(ordered_requests.len());
		for _ in 0..ordered_requests.len() {
			responses.push(Err(ErrorObject::borrowed(0, &"", None)));
		}
```

**Comment by niklasad1** [comment]
I guess we could make the batch request IDs independent of the `IdGuard` and ensure that the IDs can not wrap then I think I could get rid of this extra mess and just use `BTreeSet<Id, Result<Response, ErrorObj>>` if a u64 is used then it shouldn't wrap more likely that OOM occurs then :P

**Comment by jsdw** [comment]
Yeah; I guess I'm not worried about IDs wrapping. I mean even if the ID was a u16, a batch would have to contain >60k entries to lead to any overlap in IDs via them wrapping all the way around.

Nice workaround though :D

**Comment by niklasad1** [comment]
yeah but I as we are using a global ID guard I'm a little bit concerned if we just generate batches outside of that I'm fine with it.

I reckon that would lead to some perf improvements :)

**Comment by niklasad1** [comment]
I changed my mind it's more likely that batch requests get rejected if the request ID starts with zero for instance one might divide batch request in the same size then we will generate [1, 2, 3, 4]  for each batch and concurrent ones will be rejected.

Let's have this overflow edge-case and simplify the code.
