### ISSUE TITLE
Is there WsServerBuilder to support wss ? 

### ISSUE THREAD

**Issue by duanwujie** [paritytech/jsonrpsee#932]

**Comment by lexnv** [comment]
Hey, 

The JsonRPSee supports both the HTTP and WS connections.

Initially, when the server is started, it operates in HTTP mode.
Upon receiving an `upgrade` request, the server will execute exclusively in WS mode.

We have an example that illustrates this [ws_pubsub_broascast](https://github.com/paritytech/jsonrpsee/blob/457da328e0b4050199eca74b986a4a559159b09d/examples/examples/ws_pubsub_broadcast.rs#L67).
The upgrade request could be inspected starting the example with `RUST_LOG=trace cargo run --example ws_pubsub_broascast`.

You can then create a new `Server` similar to how it's done in that example, that will automatically
accept WS connections. 

Let us know if this solves your issue

**Comment by niklasad1** [comment]
No, @duanwujie wants to have a server running over TLS i.e, wss.

This jsonrpsee server doesn't support managing TLS certificates and similar.
You have to use nginx/reverse proxy and manage the TLS certificate and yourself.

Thus, no.

**Comment by duanwujie** [comment]
In the nginx  we can use  http to proxy ws  but not security,  is there a way like  https proxy ws ?

**Comment by niklasad1** [comment]
> In the nginx we can use http to proxy ws but not security, is there a way like https proxy ws ?

This is not anything we are giving any guidance but I can only say that it's possible you can have look at https://wiki.polkadot.network/docs/maintain-wss how to setup wss on nginx.
