### ISSUE TITLE
rpc module: `register_async_method` only allows `Copy` closures

### ISSUE THREAD

**Issue by Code0x2** [paritytech/jsonrpsee#947]
Im creating a method that will take the values, send it into a channel, and then await its response, by using register_async_method. However, it doesnt let me utilize the mpsc::UnboundedSender because it doesnt implement copy, which is a bound on the register_async_method callback. Is there some other way I can go about sending values down a channel? 

I tried register_method, but i can send that message into a channel just fine. But the problem is i want to await its response from the other end of the channel and i dont want to use a blocking recv method to do so.

**Comment by niklasad1** [comment]
hey @Code0x2 

Can you give an example what you are trying to do?
We have [this bound](https://github.com/paritytech/jsonrpsee/blob/master/core/src/server/rpc_module.rs#L580) on the closure that may you way run into.

I think it should work if you clone the sender and move into closure by `async move` but I could be wrong.

**Comment by niklasad1** [comment]
Yeah, alright seems like we need to change to bound to `Clone` instead of `Copy` of the closure

**Comment by Code0x2** [comment]
Great this fixes the problem. Thanks for the quick fix and merge!
