### ISSUE TITLE
[Feature request] Allow configure buffer size

### ISSUE THREAD

**Issue by jasl** [paritytech/jsonrpsee#958]
Hi, I'm using `Subxt` to query a very heavy custom RPC which should return a batch of raw blocks.

However, sometimes the RPC call will failed not because the node, but the jsonrpsee raise `MessageTooLarge { current: 15336981, maximum: 10485760 }` error, I don't see there's a way to set a larger `maximum`, could you add one?

**Comment by niklasad1** [comment]
Hey,

I assume this happens on the client-side and we already got an API for that: [WsClientBuilder::max_request_body_size](https://docs.rs/jsonrpsee-ws-client/latest/jsonrpsee_ws_client/struct.WsClientBuilder.html#method.max_request_body_size)

Feel free to re-open if you mean something else.

**Comment by jasl** [comment]
> Hey,
> 
> I assume this happens on the client-side and we already got an API for that: [WsClientBuilder::max_request_body_size](https://docs.rs/jsonrpsee-ws-client/latest/jsonrpsee_ws_client/struct.WsClientBuilder.html#method.max_request_body_size)
> 
> Feel free to re-open if you mean something else.

Hi, I'm not pushing large payload to RPC calls, I'm pulling a large payload, so what I'm looking for is something like `max_response_body_size`, but I don't found it.

Or I'm misunderstanding about `max_request_body_size` ?

**Comment by niklasad1** [comment]
It's poorly documented/named it applies only to the response, we rely directly on  the functionality in the websocket transport library.
