### ISSUE TITLE
It seems id is mandatory?

### ISSUE THREAD

**Issue by finlaydotb** [paritytech/jsonrpsee#964]
Making a request to a JSON RPC server built with jsonrpsee, I find out that without including `id` in the request payload, the request does not get processed and does not return any message. In this particular case this is what I get

```
curl http://localhost:8545 -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[]}' -v | jq
*   Trying 127.0.0.1:8545...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* Connected to localhost (127.0.0.1) port 8545 (#0)
> POST / HTTP/1.1
> Host: localhost:8545
> User-Agent: curl/7.84.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 53
>
} [53 bytes data]
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< content-type: application/json; charset=utf-8
< content-length: 0
< date: Fri, 06 Jan 2023 11:25:51 GMT
<
100    53    0     0  100    53      0   7313 --:--:-- --:--:-- --:--:-- 53000
* Connection #0 to host localhost left intact
```

Going through the spec here: https://www.jsonrpc.org/specification

> An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification. The value SHOULD normally not be Null [[1]](https://www.jsonrpc.org/specification#id1) and Numbers SHOULD NOT contain fractional parts [[2]](https://www.jsonrpc.org/specification#id2)

My interpretation is that, it can be omitted. Only that if not omitted then its value needs to be a String, Number, or NULL value.

Is there a way to configure jsonrpsee to not have the id as mandatory?

**Comment by niklasad1** [comment]
Hey @finlaydotb 

> An identifier established by the Client that MUST contain a String, Number, or NULL value if included. If it is not included it is assumed to be a notification

Thus, a request without an ID is regarded as notification

> A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. The Server MUST NOT reply to a Notification, including those that are within a batch request.

So, no it's not possible to configure jsonrpsee to reply to "requests without ID" as it would not comply with the JSON-RPC v2 spec.
Thus, I don't agree with your interpretation.

**Comment by finlaydotb** [comment]
@niklasad1 

I over looked the sentence about the notification. And on further reading the spec, I see

> A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. The Server MUST NOT reply to a Notification, including those that are within a batch request.

So yeah I stand corrected. If the client is expecting a response, then the Id should be set.
