### ISSUE TITLE
Using futures::future::pending::<()>().await to generate an endless loop in main.rs

### ISSUE THREAD

**Issue by Eikix** [paritytech/jsonrpsee#969]
Hey all:)!

I'm a jsonrpsee newbie, I saw in some [examples](https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/tokio_console.rs) that in order to keep the server running indefinitely, one can use `futures::future::pending::<()>().await`. 

I read that it is not a good idea to use a future that never resolves to keep the server running. Is it true?

Is there a better way than:

```rust
use eyre::Result;
use futures::future::pending;

#[tokio::main]
async fn main() -> Result<()> {
    let server_addr = run_server().await?;
    println!("{server_addr}");
    pending::<()>().await;
    Ok(())
}

```

**Comment by lexnv** [comment]
Hi,

We are using the `	futures::future::pending().await` pending future to make sure that the main function does not exit, terminating in result the process together with the RPC server.

That is for example purposes only. Ideally, you can have an RPC server running for as long as you need it in your own process.

When the JsonRPSee server starts, it will spawn a new tokio task to handle in the background request and response messages. You can tell your RPC server to stop either when: 
- call the [stop](https://github.com/paritytech/jsonrpsee/blob/2c2abcb807c3b7688daedf8aaa3308da77cb8c11/server/src/future.rs#L183) method
- drop the [ServerHandle](https://github.com/paritytech/jsonrpsee/blob/2c2abcb807c3b7688daedf8aaa3308da77cb8c11/server/src/future.rs#L174)

https://github.com/paritytech/jsonrpsee/blob/2c2abcb807c3b7688daedf8aaa3308da77cb8c11/server/src/future.rs#L169-L174

We are moving in our examples the server handle to a separate task to make sure it is not dropped by:
`tokio::spawn(handle.stopped());` Tho, you can keep the handle around in your main task.

You can imagine a scenario where you have the RPC server running and your main does some business logic. That is highly dependent on your use-case. 

```rust
async fn main() {
    server_handle = init_server();

    loop { 
       if condition { 
           server_handle.stop();
            // ...
        }
    }
}
```

**Comment by lexnv** [comment]
Anytime! Let us know if you have any other questions or if we could offer any support!

**Comment by Eikix** [comment]
I arrived at something that looks like this, although it's a bit ugly;P

```rust
pub async fn run_server() -> Result<(SocketAddr, ServerHandle)> {
    let server = ServerBuilder::default().build("127.0.0.1:0").await?;

    let addr = server.local_addr()?;
    let handle = server.start(KakarotEthRpc.into_rpc())?;

    Ok((addr, handle))
}

#[tokio::main]
async fn main() -> Result<()> {
    let (server_addr, server_handle) = run_server().await?;
    println!("{server_addr}");

    let condition = false;
    loop {
        if condition {
            server_handle.stop();
        }
    }

    Ok(())
}
```

**Comment by jsdw** [comment]
In general, I'd suggest that `pending::<()>().await;` is generally jsut used as a placeholder for "various other async things that can happen here". It's no issue from a performance POV, but from a logic POV it means we have a process that runs forever even if the server stops in the background or whatever, which is obviously not ideal.

I think that `handle` (ie the result of `server.start(..)`) has an `async fn stopped()` on it, so a fairly sensible "default" to end your main function with would be somehting like:

```rust
pub async fn run_server() -> Result<(SocketAddr, ServerHandle)> {
    let server = ServerBuilder::default().build("127.0.0.1:0").await?;

    let addr = server.local_addr()?;
    let handle = server.start(KakarotEthRpc.into_rpc())?;

    Ok((addr, handle))
}

#[tokio::main]
async fn main() -> Result<()> {
    let (server_addr, server_handle) = run_server().await?;
    println!("{server_addr}");

    server_handle.stopped().await;
    Ok(())
}
```

But of course if you have other things you'd like to run and wait for, you may end up `join`ing that `server_handle.stopped()` with other futures. But it's ultiamtely up to you and what you want to happen :)

**Comment by Eikix** [comment]
Ahhh thanks:)!

**Comment by niklasad1** [comment]
Closing this issue as resolved, but I think we should change the example to use `server_handle.stopped()` instead of `future::pending` as James pointed.

We are happy to accept PRs :)
