### ISSUE TITLE
Handling response data

### ISSUE THREAD

**Issue by allquixotic** [paritytech/jsonrpsee#976]
Let's say I have a json-rpc call, where the server returns a payload like the below.

I only care about the "session_id" parameter. The rest can be thrown away.

To use jsonrpsee (in rpc proc mode or directly using the client; I don't especially care), do I have to create structs of structs mapping out this entire data payload in an object graph? 

Or, can I set an `HttpClient.request` result type to something simple that allows me to just get the session_id?

Is it easier or better to do it using the rpc macro?

I'm OK getting away from type safety, and doing something like:

`let generic_response = client.do_something(foo).await;`

then

`let session_id: Option<String> = generic_response.try_get("session_id");`

Problem is, I just don't know what data type to specify in the return value to _get_ that kind of response.

With the bare HTTP client (i.e., not using the RPC macro), I have the same problem with the `params: Params` of the `ClientT::request` method. What type do I use if I want to specify `params: { "email": "foo", "password": "bar" }`? 

Certainly it doesn't seem right to use a `Vec` like the `rpc_params!` macro seems to expect, right? Because how could it transform a vec like `rpc_params! [ "email", "foo", "password", "bar" ]` into `params: { "email": "foo", "password": "bar" }`?

BTW, none of this really seems to be documented. The library appears to be designed with only one use case in mind, of handling scalar data type responses (like a u64), which is not what this website does at all. Better documentation or any help is greatly appreciated.

```
{
    "result": {
        "session_id": "redacted",
        "notification_counts": {
            "mail": "0",
            "notifications": "15",
            "applications": "2",
            "pending_friend_requests": 0,
            "api-general": "2",
            "api-forums": "255"
        },
        "pusher_channels": {
            "pubnub_channel": "pubnub-mobile-redacted",
            "channel_user": "user_redacted_0",
            "channel_site": "presence-site",
            "channel_sitewall_post": "sitewall_post",
            "channel_chat": "presence-pchat"
        },
        "user_id": "redacted",
        "language": "en",
        "username": "redacted",
        "resources": "https://resources.enjin.com/redacted/",
        "sites": [
            {
                "site_id": "redacted",
                "name": "redacted",
                "url": "http://www.enjin.com",
                "description": "",
                "logo": "https://s3.amazonaws.com/files.enjin.com/redacted/site_logo/large.png",
                "logo_full": "https://s3.amazonaws.com/files.enjin.com/redacted/site_logo/full.png",
                "likes": "370",
                "is_liked": false,
                "users": "redacted",
                "banner": "https://resources.enjin.com/redacted/admin/v3/images/settings/default_banner.png",
                "access": "2",
                "can_join": true
            }
        ]
    },
    "id": "1",
    "jsonrpc": "2.0"
}
```

**Comment by niklasad1** [comment]
Closing this issue because all you want is already in the library but as you said it the documentation could/should be better.

**Comment by allquixotic** [comment]
Thank you for the feedback. That helps me a lot.
