### ISSUE TITLE
Issue with client blocking when results array > 32 items

### ISSUE THREAD

**Issue by thepacketgeek** [paritytech/jsonrpsee#98]
I have an [RPC API Defined](https://github.com/thepacketgeek/bgpd-rs/blob/master/rpc_lib/src/lib.rs#L10), and I've noticed that a client can hit 100% CPU awaiting the result for `show_routes_learned` [here](https://github.com/thepacketgeek/bgpd-rs/blob/master/examples/cli/src/main.rs#L212).

After much testing by changing the amount of data that's being returned (by altering advertised routes from a BGP peer) I found the following:
-  I can reliably re-pro the blocking client and pegged CPU with 33+ items ([example payload](https://pastebin.com/BzkE9ADL)).
- When I have 32 or fewer items, the client behaves fine ([example payload](https://pastebin.com/TrMbRyuT))
- I've mixed and matched different advertised routes and the one thing that is consistent is when I hit 33 or more items, the client blocks on the `show_routes_learned` call above.
- I know it's the client library because I can get the results from the server from Postman for 33+ results just fine.
- This seems to have broken sometime in the last month or so

I know this seems like a strange issue, please let me know if there's any other info I can provide to help troubleshoot!

**Comment by niklasad1** [comment]
@thepacketgeek why did you close this issue? 

We should fix it, can you report which transport you are using (HTTP or WebSocket)?

**Comment by thepacketgeek** [comment]
Oh, sorry, I thought it was a bad issue (no repro)! I will try to create a minimal repro example and add it shortly.
