### ISSUE TITLE
"Invalid response ID" error despite 200/OK response?

### ISSUE THREAD

**Issue by allquixotic** [paritytech/jsonrpsee#980]
In [the attached Gist](https://gist.github.com/allquixotic/accb7721036062581c7c98ffce9b252b) where my code is based on [PR #975](https://github.com/paritytech/jsonrpsee/pull/975), you can see that:

 - The request body is valid,
 - The server likes the request and returns a valid response with 200/OK,
 - The deserialization logic of the response seems able to parse out the `session_id`, since if I change the name of the parameter in the `LoginResponse` to `nonexistent` I get an error that it can't parse out that result.

```
Error: Parse error: missing field `nonexistent` at line 1 column 1449

Caused by:
    missing field `nonexistent` at line 1 column 1449
```

OK, so because my working code **doesn't** throw that error, it's able to parse out the session_id. Great! 

**So why is it _still_ throwing an Error up the stack?!**

It has been such a battle just to get one request to come back successfully :(

**Comment by niklasad1** [comment]
> So why is it still throwing an Error up the stack?!

I don't understand what is going on, I tried your example but the error says `Error: RPC call failed: ErrorObject { code: ServerError(-32099), message: "Invalid email or password.", data: None }`

Can you please update the logs?

**Comment by allquixotic** [comment]
> > So why is it still throwing an Error up the stack?!
> 
> I don't understand what is going on, I tried your example but the error says `Error: RPC call failed: ErrorObject { code: ServerError(-32099), message: "Invalid email or password.", data: None }`
> 
> Can you please update the logs?

In order to repro this issue, you would need to supply a valid email/password from a (free) enjin.com forum account. However, I don't expect you to go through the trouble, especially because it appears you have successfully diagnosed the error!

Yes, at something like 3am local time, I was looking at the request and the response, and I didn't see the difference between `"id":0` and `"id":"0"`. Now that you point it out, it's quite obvious, and the Error description makes perfect sense.

Once I set `IdKind::String` on the HttpClientBuilder, it *works*! It actually works! 👍🏻 

You folks have been *very* helpful in the issues here while I've been learning how to use this crate. Thanks so much!


> 
> EDIT:
> 
> I see now, the server returns ID `"id":"0"` but request actually specified `"id":0` that's why you get `Error::InvalidRequestId` as we are strict and doesn't regard `0` == `"0"`
> 
> Try https://docs.rs/jsonrpsee-http-client/0.16.2/jsonrpsee_http_client/struct.HttpClientBuilder.html#method.id_format configure the ID as String format instead that should probably work.
