### ISSUE TITLE
How to setup middleware for WebSocket requests/responses

### ISSUE THREAD

**Issue by xlc** [paritytech/jsonrpsee#982]
I would like to for example have a caching middleware handling both HTTP and WebSocket requests. I can see how to do it for the HTTP part but not the WebSocket part.

**Comment by niklasad1** [comment]
The middleware/[tower](https://docs.rs/tower/latest/tower/) itself does only apply to the to `HTTP part` so for WebSockets it applies only to WebSocket handshake. Thus, when it's upgraded to a Websocket connection there is no middleware capabilities to do middleware caching unfortunately.  

This is nothing really that we have thought about but how would decide what to cache? By `method name and params`?  I reckon that we need to some special middleware to avoid users to decode the JSON messages to JSON-RPC requests... 

We should add a better description for the middleware API docs anyway.

**Comment by xlc** [comment]
This is the middleware interface I created: https://github.com/AcalaNetwork/subway/blob/master/src/middleware/mod.rs
Usage: https://github.com/AcalaNetwork/subway/blob/4fc13fb1cacaf4e1827a2f9cd2ab41b14b179910/src/server.rs#L63

Will need to adjust it to make https://github.com/paritytech/jsonrpsee/issues/1000 possible
