### ISSUE TITLE
How to reconnect

### ISSUE THREAD

**Issue by xlc** [paritytech/jsonrpsee#988]
I understand auto reconnect is out of scope for this library and that's fine. However how to implement it in my application? I can't find connect/reconnect method. Do I need to make a new ws client to reconnect?

**Comment by niklasad1** [comment]
> Do I need to make a new ws client to reconnect?

Yes unfortunately, the connect is called on the hood in https://docs.rs/jsonrpsee-ws-client/0.16.2/jsonrpsee_ws_client/struct.WsClientBuilder.html#method.build
