### ISSUE TITLE
Fix crates.io crate version

### ISSUE THREAD

**Issue by Morgan-iv** [paritytech/jsonrpsee#99]
Now, the [crates.io](https://crates.io/crates/jsonrpsee) version of this crate is 0.1.0, but version 1.0.0 specified in Cargo.toml. I think, crates.io version should be specified as 1.0.0

**Comment by niklasad1** [comment]
Hey, we are not ready to release `1.0` and first next release will be `0.2`.

We have tracking issue for that in #251 so closing this
