### ISSUE TITLE
Disjunctive/union type for deserialize and rpc macro?

### ISSUE THREAD

**Issue by allquixotic** [paritytech/jsonrpsee#991]
I am using jsonrpsee with the HTTP client.

There is a JSON-RPC API (that I can't change; the server is not owned by me) that returns two different "shapes" of data for the same API call, in the `result`:

## Shape 1

```
"foo": [],
...
```

## Shape 2

```
"foo": {
  "bar": {
    "prop1": "val1",
    "prop2": "val2",
    "prop3": "val3",
    ...
  }
}
```

I have bound the method as follows:

```
#[derive(Deserialize)]
pub struct GetBarResult {
    pub foo: HashMap<String, HashMap<String, PropertyColl>>,
    ... etc
}


#[rpc(client)]
trait FooApi {
    #[method(name="Foo.getBar", param_kind=map)]
    async fn get_foo(
        &self,
        param_id: &String,
    ) -> Result<GetBarResult, Error>;
```

where `PropertyColl` is another `struct` that collects the "prop1", "prop2", etc. properties as in `Shape 2`.

It would be a lot of work to manually parse out all the data based on `serde_json::Value` because of the depth of the data for `Shape 2`. It would also be inefficient and undesirable to do something like (pseudocode):

```
let gbr: Result<GetBarResult, Error> = client.get_foo("1234".to_string()); 
match gbr {
  Ok(gb) => {
    // Do something with `gb`
  },
  Err(e) => {
    let alt = Result<GetOtherBarResult, Error> = client.get_other_foo("1234".to_string());
    //...Do something with `alt`
  }
}
```

Is there an easy way to:

 - Issue *only one* JSON-RPC HTTP request;
 - Parse out the value with the "shape" of the data differing in a way that cannot be predicted (i.e., I can't know before making the request which shape the data will come back as);
 - Gather the output into the appropriate data structure using jsonrpsee's rpc/method macros and not using dynamic/late-bound parsing with `serde_json::Value`.

Or do  I need to use one of the workarounds I mentioned, or some better workaround?

For the purposes of this question, assume that I am already aware of all possible "data shapes" that may come back from a given request. Maybe there are 2 possible shapes, maybe there are 50, but I know them all.

I just can't predict _at request time_ which of the possible shapes will be sent back to me.

**Comment by niklasad1** [comment]
> For the purposes of this question, assume that I am already aware of all possible "data shapes" that may come back from a given request. Maybe there are 2 possible shapes, maybe there are 50, but I know them all.
Or do I need to use one of the workarounds I mentioned, or some better workaround?

This is more question how to use serde, if there only two shapes it should quite easy to use https://serde.rs/enum-representations.html#internally-tagged i.e, use `foo` as a tag.

If you have n different shapes of the message, I have no good answer rather than to write a macro that takes all shapes as input and generates an aggregate type for you.

I can't see how we can make this easier as we are tied to serde.

**Comment by allquixotic** [comment]
Thanks - just the information that "the answer is the same as for pure serde" is enough for me. I didn't know if jsonrpsee has any additional requirements or expectations on top of what serde does, and I didn't actually know about how serde handles different shapes until you linked the documentation there.

Appreciate it.
